package scenariogen

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ondatra-ai/true-bdd/pkg/disk"
	"github.com/ondatra-ai/true-bdd/services/bdd-cli/internal/infrastructure/architecture"
	"github.com/ondatra-ai/true-bdd/services/bdd-cli/internal/infrastructure/registry"
)

const (
	suiteName    = "bdd-cli"
	webSuite     = "bdd-web"
	suitePath    = "tests/bdd-cli"
	testFile     = "tests/bdd-cli/build_code_test.go"
	registryPath = "docs/scenarios.yaml"
)

// arch is a one-suite spec: the cli suite, on go-test, at tests/bdd-cli.
func arch() *architecture.Architecture {
	return &architecture.Architecture{
		Suites: []architecture.Suite{{
			Name: suiteName, Service: suiteName, Path: suitePath, Framework: FrameworkGoTest,
		}},
		Services: []architecture.Service{{Name: suiteName, Path: "services/bdd-cli", Language: "go"}},
	}
}

// scenario builds one registry entry with a single Given step.
func scenario(id, path string) *registry.RegistryScenario {
	return &registry.RegistryScenario{
		ID: id, Description: "one", Service: suiteName, Path: path,
		Statements: []registry.Statement{{Keyword: registry.KeywordGiven, Text: "a tree"}},
	}
}

// repoWithModule returns a temp dir holding a go.mod, so the import path
// of a suite's shim can be computed.
func repoWithModule(t *testing.T) string {
	t.Helper()

	root := t.TempDir()

	err := disk.Write(filepath.Join(root, "go.mod"), []byte("module example.com/repo\n"), disk.Shared)
	if err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	err = disk.Dir(filepath.Join(root, suitePath), disk.Shared)
	if err != nil {
		t.Fatalf("create suite dir: %v", err)
	}

	return root
}

// planOne builds a plan for a single scenario, failing the test on any
// refusal.
func planOne(t *testing.T, item *registry.RegistryScenario) (*Plan, string) {
	t.Helper()

	root := repoWithModule(t)

	plan, err := BuildPlan([]*registry.RegistryScenario{item}, arch(), root, registryPath)
	if err != nil {
		t.Fatalf("BuildPlan: %v", err)
	}

	return plan, root
}

// The ordinary case: a scenario renders a compiling Go test that names
// itself, imports the suite's shim, and states its steps as literals.
func TestRenderEmitsAGeneratedTest(t *testing.T) {
	t.Parallel()

	plan, _ := planOne(t, scenario("E2E-001", testFile))

	source, err := Render(plan.Files[0])
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	for _, want := range []string{
		"//go:build bdd",
		"// Code generated by `true-bdd build tests`. DO NOT EDIT.",
		"package bddcli_test",
		`"example.com/repo/tests/bdd-cli/scenarios"`,
		`func TestE2E001(t *testing.T) {`,
		`s := scenarios.New(t, "E2E-001")`,
		"s.Given(`a tree`)",
		"s.Done()",
	} {
		if !strings.Contains(string(source), want) {
			t.Errorf("rendered file is missing %q:\n%s", want, source)
		}
	}
}

// Step text is a raw string so the "quoted" runs and regex escapes a
// scenario is full of survive unescaped — that is what keeps the file
// reading like the scenario it transcribes.
func TestRenderPrefersRawStringLiterals(t *testing.T) {
	t.Parallel()

	item := scenario("E2E-001", testFile)
	item.Statements[0].Text = `stdout matches level=ERROR msg="Refusing to start" \(x\)`

	plan, _ := planOne(t, item)

	source, err := Render(plan.Files[0])
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	want := "s.Given(`" + item.Statements[0].Text + "`)"
	if !strings.Contains(string(source), want) {
		t.Errorf("want the raw literal %q:\n%s", want, source)
	}
}

// A backtick makes a raw string impossible, so the quoted form takes
// over rather than emitting source Go would not parse.
func TestLiteralFallsBackToQuotingOnABacktick(t *testing.T) {
	t.Parallel()

	got := literal("stdout matches `true-bdd build tests`")

	want := `"stdout matches ` + "`" + `true-bdd build tests` + "`" + `"`
	if got != want {
		t.Errorf("literal() = %s, want %s", got, want)
	}
}

// Two scenarios sharing a path land in one file, in id order — not the
// document's order, which a YAML map decode has already lost.
func TestBuildPlanGroupsByPathInIDOrder(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	plan, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-002", testFile),
		scenario("E2E-001", testFile),
	}, arch(), root, registryPath)
	if err != nil {
		t.Fatalf("BuildPlan: %v", err)
	}

	if len(plan.Files) != 1 {
		t.Fatalf("want one file, got %d", len(plan.Files))
	}

	ids := []string{plan.Files[0].Scenarios[0].ID, plan.Files[0].Scenarios[1].ID}
	if ids[0] != "E2E-001" || ids[1] != "E2E-002" {
		t.Errorf("want id order, got %v", ids)
	}
}

// Everything a `path:` can be wrong about, refused by name: each produces a
// file that compiles into the wrong package, overwrites something it must
// not, or does not compile at all — so none of them can be a warning.
func TestBuildPlanRefusesABadPath(t *testing.T) {
	t.Parallel()

	cases := map[string]struct {
		path string
		want error
	}{
		"absent":          {"", ErrNoPath},
		"absolute":        {"/tmp/x_test.go", ErrPathNotRelative},
		"escaping":        {"../x_test.go", ErrPathNotRelative},
		"not a test file": {"tests/bdd-cli/x.go", ErrPathNotTestFile},
		"another suite":   {"tests/bdd-web/x_test.go", ErrPathNotInSuiteRoot},
		"a subdirectory":  {"tests/bdd-cli/sub/x_test.go", ErrPathNotInSuiteRoot},
	}

	for name, testCase := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			root := repoWithModule(t)

			_, err := BuildPlan([]*registry.RegistryScenario{
				scenario("E2E-001", testCase.path),
			}, arch(), root, registryPath)

			if !errors.Is(err, testCase.want) {
				t.Fatalf("want %v, got %v", testCase.want, err)
			}
		})
	}
}

// The steps/ tree belongs to the fix turn. A generated file written into
// it could overwrite a step definition, and the definitions are the one
// thing here no regeneration can reproduce.
func TestBuildPlanRefusesThePathInsideTheStepsTree(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", "tests/bdd-cli/steps/x_test.go"),
	}, arch(), root, registryPath)

	// Caught as "not in the suite root" first, which is the same refusal
	// for the same reason; what matters is that it never renders.
	if err == nil {
		t.Fatal("want a refusal for a path inside steps/, got nil")
	}
}

// Two scenarios sharing one file must belong to one suite — the file is one
// Go package bound to one suite's state. Reachable only when two suites
// declare the SAME root; different roots are already caught by the per-scenario path check.
func TestBuildPlanRefusesTwoServicesInOneFile(t *testing.T) {
	t.Parallel()

	other := scenario("E2E-002", testFile)
	other.Service = webSuite

	spec := arch()
	spec.Suites = append(spec.Suites, architecture.Suite{
		Name: webSuite, Service: webSuite, Path: suitePath, Framework: FrameworkGoTest,
	})

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile), other,
	}, spec, root, registryPath)

	if !errors.Is(err, ErrPathCrossSuite) {
		t.Fatalf("want ErrPathCrossSuite, got %v", err)
	}
}

// Two ids that render one Go name would make `-run TestE2E001`
// ambiguous and, in one file, would not compile at all.
func TestBuildPlanRefusesCollidingIdentifiers(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile),
		scenario("E2E001", testFile),
	}, arch(), root, registryPath)

	if !errors.Is(err, ErrIdentifierCollision) {
		t.Fatalf("want ErrIdentifierCollision, got %v", err)
	}
}

// A scenario naming a service no suite declares is a behaviour nothing
// runs, so it is refused rather than rendered into a file no suite owns.
func TestBuildPlanRefusesAnUnknownService(t *testing.T) {
	t.Parallel()

	item := scenario("E2E-001", testFile)
	item.Service = "nobody"

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{item}, arch(), root, registryPath)
	if !errors.Is(err, ErrNoSuiteForService) {
		t.Fatalf("want ErrNoSuiteForService, got %v", err)
	}
}

// A framework with no renderer is named, not skipped: a suite quietly
// left ungenerated is a suite whose scenarios nothing executes.
func TestBuildPlanRefusesAnUnrenderableFramework(t *testing.T) {
	t.Parallel()

	spec := arch()
	spec.Suites[0].Framework = "jest"

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile),
	}, spec, root, registryPath)

	if !errors.Is(err, ErrNoGeneratorForFramework) {
		t.Fatalf("want ErrNoGeneratorForFramework, got %v", err)
	}
}

// A scenario with no steps would render a test that names a behaviour,
// asserts nothing, and passes.
func TestBuildPlanRefusesAStepless(t *testing.T) {
	t.Parallel()

	item := scenario("E2E-001", testFile)
	item.Statements = nil

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{item}, arch(), root, registryPath)
	if !errors.Is(err, ErrScenarioHasNoSteps) {
		t.Fatalf("want ErrScenarioHasNoSteps, got %v", err)
	}
}

// Writing is idempotent, so a regeneration that changed nothing touches
// no mtime — which is what a build cache and a file watcher key on.
func TestWriteIsIdempotent(t *testing.T) {
	t.Parallel()

	plan, root := planOne(t, scenario("E2E-001", testFile))

	written, err := Write(plan, root)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}

	if len(written) != 1 {
		t.Fatalf("want one file written, got %v", written)
	}

	written, err = Write(plan, root)
	if err != nil {
		t.Fatalf("Write again: %v", err)
	}

	if len(written) != 0 {
		t.Errorf("want nothing rewritten, got %v", written)
	}

	drifted, err := Verify(plan, root)
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}

	if len(drifted) != 0 {
		t.Errorf("want no drift after writing, got %v", drifted)
	}
}

// A typo'd `path:` pointing at a step definition must not delete it.
func TestWriteRefusesToClobberAHandWrittenFile(t *testing.T) {
	t.Parallel()

	plan, root := planOne(t, scenario("E2E-001", testFile))

	target := filepath.Join(root, filepath.FromSlash(testFile))

	err := disk.Write(target, []byte("package steps\n\n// hand written\n"), disk.Shared)
	if err != nil {
		t.Fatalf("seed: %v", err)
	}

	_, err = Write(plan, root)
	if !errors.Is(err, ErrWouldClobberHandWritten) {
		t.Fatalf("want ErrWouldClobberHandWritten, got %v", err)
	}

	after, err := disk.Read(target)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}

	if !strings.Contains(string(after), "hand written") {
		t.Error("the hand-written file was overwritten")
	}
}

// A missing file and a stale one are both drift, and each says which.
func TestVerifyReportsMissingAndStale(t *testing.T) {
	t.Parallel()

	plan, root := planOne(t, scenario("E2E-001", testFile))

	drifted, err := Verify(plan, root)
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}

	if len(drifted) != 1 || !strings.Contains(drifted[0].Reason, "no generated test file") {
		t.Fatalf("want a missing-file drift, got %v", drifted)
	}

	_, err = Write(plan, root)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}

	target := filepath.Join(root, filepath.FromSlash(testFile))

	source, err := disk.Read(target)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	err = disk.Write(target, append(source, byte('\n')), disk.Shared)
	if err != nil {
		t.Fatalf("perturb: %v", err)
	}

	drifted, err = Verify(plan, root)
	if err != nil {
		t.Fatalf("Verify again: %v", err)
	}

	if len(drifted) != 1 || !strings.Contains(drifted[0].Reason, "not what the registry renders") {
		t.Fatalf("want a stale-file drift, got %v", drifted)
	}
}

// An id whose Go name `go test` would compile and never run is refused —
// see checkRunnableTestName: the worst failure available, since every
// coverage check still reports the scenario as covered.
func TestBuildPlanRefusesAnUnrunnableTestName(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("int-900", testFile),
	}, arch(), root, registryPath)

	if !errors.Is(err, ErrUnrunnableTestName) {
		t.Fatalf("want ErrUnrunnableTestName, got %v", err)
	}

	if !strings.Contains(err.Error(), "Testint900") {
		t.Errorf("the refusal must name what it would have rendered, got %q", err)
	}
}

// A path with surrounding whitespace passes every trimmed check and then
// lands on disk with the space in the filename — a file `go test`
// ignores and Verify reports as drifted forever.
func TestBuildPlanRefusesAPathWithWhitespace(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile+" "),
	}, arch(), root, registryPath)

	if !errors.Is(err, ErrPathNotRelative) {
		t.Fatalf("want ErrPathNotRelative, got %v", err)
	}
}

// The steps/ tree gets its own refusal rather than the generic
// suite-root one: which tree you landed in is the whole diagnosis, and
// that tree is the one no regeneration could rebuild.
func TestBuildPlanNamesTheStepsTree(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", suitePath+"/steps/x_test.go"),
	}, arch(), root, registryPath)

	if !errors.Is(err, ErrPathInStepsTree) {
		t.Fatalf("want ErrPathInStepsTree, got %v", err)
	}
}

// Renaming a suite re-derives the package name — see checkPackageClause:
// without a check, regeneration writes a mismatched package and the suite
// stops compiling with nothing pointing at the rename.
func TestBuildPlanRefusesAPackageClauseMismatch(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	err := os.WriteFile(filepath.Join(root, suitePath, "main_test.go"),
		[]byte("package bddcli_test\n"), 0o600)
	if err != nil {
		t.Fatalf("seed: %v", err)
	}

	spec := arch()
	spec.Suites[0].Name = "cli"

	_, err = BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile),
	}, spec, root, registryPath)

	if !errors.Is(err, ErrPackageClauseMismatch) {
		t.Fatalf("want ErrPackageClauseMismatch, got %v", err)
	}
}

// A suite name that derives no legal Go identifier is named here rather
// than surfacing later as a parse error from format.Source that names
// nothing.
func TestBuildPlanRefusesAnInvalidPackageName(t *testing.T) {
	t.Parallel()

	root := repoWithModule(t)

	spec := arch()
	spec.Suites[0].Name = "2e2"

	_, err := BuildPlan([]*registry.RegistryScenario{
		scenario("E2E-001", testFile),
	}, spec, root, registryPath)

	if !errors.Is(err, ErrPackageNameInvalid) {
		t.Fatalf("want ErrPackageNameInvalid, got %v", err)
	}
}
