//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-015: A registry that parses but holds no scenarios must be refused, never walked to a trivial success
func TestE2E015(t *testing.T) {
	s := scenarios.New(t, "E2E-015")
	s.Given(`the "build-tests-empty-registry" project tree`)
	s.When(`the System Architect runs "build tests"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches BUILD TESTS`)
	s.And(`stdout matches Cannot start: .*requirements registry has no scenarios to walk`)
	s.And(`stdout matches docs/scenarios\.yaml: requirements registry has no scenarios to walk`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="build tests"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-016: A registry scenario with no test must get a generated test file and a step definition for every step it declares
func TestE2E016(t *testing.T) {
	s := scenarios.New(t, "E2E-016")
	s.Given(`the "build-tests-fix-happy-path" project tree`)
	s.And(`the System Architect answers "1" to every prompt`)
	s.When(`the System Architect runs "build tests --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`the file "tests/mcp/mcp_test.go" is created`)
	s.And("the file \"tests/mcp/mcp_test.go\" matches // Code generated by `true-bdd build tests`\\. DO NOT EDIT\\.")
	s.And(`the file "tests/mcp/mcp_test.go" matches scenarios\.New\(t, "INT-900"\)`)
	s.And(`exactly 1 file matching "tests/mcp/steps/*.go" is created`)
	s.And(`every step of scenario "INT-900" in "docs/scenarios.yaml" is matched by a step definition under "tests/mcp/steps"`)
	s.But(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`no file outside "tmp" and "tests" changed`)
	s.Done()
}

// E2E-017: A registry that is valid YAML but the wrong SHAPE must be refused with the decoder's own complaint, not a generic parse failure
func TestE2E017(t *testing.T) {
	s := scenarios.New(t, "E2E-017")
	s.Given(`the "build-tests-malformed-registry" project tree`)
	s.When(`the System Architect runs "build tests"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches BUILD TESTS`)
	s.And(`stdout matches Cannot start: .*failed to parse requirements registry .*docs/scenarios\.yaml: yaml: unmarshal errors:`)
	s.And(`stdout matches cannot unmarshal !!seq into map\[string\]`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="build tests"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-018: A host that never declared where its scenario registry lives must be refused, never quietly served the conventional path
func TestE2E018(t *testing.T) {
	s := scenarios.New(t, "E2E-018")
	s.Given(`the "build-tests-unconfigured-registry" project tree`)
	s.When(`the System Architect runs "build tests"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches Cannot start: resolve scenario registry`)
	s.And(`stdout matches documents\.scenarios_yaml`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-019: Multi-provider routing must fail LOUDLY, never quietly
func TestE2E019(t *testing.T) {
	s := scenarios.New(t, "E2E-019")
	s.Given(`the "build-tests-unknown-cli-tier" project tree`)
	s.When(`the System Architect runs "build tests"`)
	s.Then(`the command exits with code 1`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}
