//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-001: A command the spec states correctly but the machine cannot run must fail loudly, and on stdout
func TestE2E001(t *testing.T) {
	s := scenarios.New(t, "E2E-001")
	s.Given(`the "build-code-command-not-executable" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches msg="Cannot run suite" suite=calc/e2e`)
	s.And(`stdout matches true-bdd-no-such-runner`)
	s.And(`stdout matches discovery failed`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned the test runner "true-bdd-no-such-runner"`)
	s.And(`the engine spawned exactly 1 test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-002: A command that runs fine but cannot be parsed must be refused
func TestE2E002(t *testing.T) {
	s := scenarios.New(t, "E2E-002")
	s.Given(`the "build-code-command-not-machine-readable" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches must emit machine-readable output`)
	s.And(`stdout matches is missing -json`)
	s.And(`stdout matches calc/e2e`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-003: `build code` must run the command its architectural spec declares — and specifically the `replay` one
func TestE2E003(t *testing.T) {
	s := scenarios.New(t, "E2E-003")
	s.Given(`the "build-code-commands-from-spec" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches msg="Running tests" suite=calc/e2e framework=go-test`)
	s.And(`stdout matches msg="Suite failures" failures=0 suite=calc/e2e`)
	s.And(`stdout matches msg="Total failing tests across architecture" failures=0`)
	s.And(`stdout matches BUILD CODE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned a test runner with arguments matching -run \^TestGreen\$`)
	s.And(`the engine spawned exactly 1 test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-004: A suite command that is present but names no program must be refused
func TestE2E004(t *testing.T) {
	s := scenarios.New(t, "E2E-004")
	s.Given(`the "build-code-empty-command" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches calc/e2e: test suite command is empty`)
	s.And(`stdout matches test suite command is empty: \\"''\\"`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="build code"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-005: After a fix is applied, `build code` must re-run THE TEST IT FIXED — not the whole suite
func TestE2E005(t *testing.T) {
	s := scenarios.New(t, "E2E-005")
	s.Given(`the "build-code-fix-named-test" project tree`)
	s.And(`the System Architect answers "1" to every prompt`)
	s.When(`the System Architect runs "build code --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches msg="Running tests" suite=calc/e2e framework=go-test`)
	s.And(`stdout matches msg="Suite failures" failures=1 suite=calc/e2e`)
	s.And(`stdout matches msg="Total failing tests across architecture" failures=1`)
	s.And(`stdout matches msg="Fix applied; re-running this test in isolation"`)
	s.And(`stdout matches BUILD CODE COMPLETE`)
	s.And(`the file "services/calc/calc.go" is modified`)
	s.And(`the file "tests/suite/suite-runs.log" has exactly 1 line`)
	s.And(`the engine spawned a test runner with arguments matching TestAddSumsItsArguments`)
	s.But(`the file "tests/suite/add_test.go" is unchanged`)
	s.And(`the file "tests/suite/canary_test.go" is unchanged`)
	s.And(`the file "docs/architecture/architecture.yaml" is unchanged`)
	s.And(`the command "go test -json -count=1 ./tests/suite/..." run in "." exits with code 0`)
	s.Done()
}

// E2E-006: A spec the loader cannot decode must be refused with the file named
func TestE2E006(t *testing.T) {
	s := scenarios.New(t, "E2E-006")
	s.Given(`the "build-code-malformed-spec" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches failed to parse architecture file`)
	s.And(`stdout matches docs/architecture/architecture\.yaml`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/architecture/architecture.yaml" is unchanged`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-007: A test suite that does not say how to run itself must be refused, not run some other way
func TestE2E007(t *testing.T) {
	s := scenarios.New(t, "E2E-007")
	s.Given(`the "build-code-missing-suite-command" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches commands\.replay`)
	s.And(`stdout matches architecture\.testing\.suites\[e2e\]`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-008: An architectural spec that declares no services at all must be refused, not walked to a trivial success
func TestE2E008(t *testing.T) {
	s := scenarios.New(t, "E2E-008")
	s.Given(`the "build-code-no-services" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches no services to walk`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-009: An architectural spec that declares no test suites must be refused, not walked to a trivial success
func TestE2E009(t *testing.T) {
	s := scenarios.New(t, "E2E-009")
	s.Given(`the "build-code-no-suites" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches no test suites to walk`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-010: A walk that ends with a test still failing must exit non-zero
func TestE2E010(t *testing.T) {
	s := scenarios.New(t, "E2E-010")
	s.Given(`the "build-code-nonconvergence" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches msg="Running tests" suite=calc/e2e framework=go-test`)
	s.And(`stdout matches msg="Suite failures" failures=1 suite=calc/e2e`)
	s.And(`stdout matches msg="Total failing tests across architecture" failures=1`)
	s.And(`stdout matches BUILD CODE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned the test runner "go"`)
	s.And(`the engine dispatched 1 AI turn`)
	s.Done()
}

// E2E-011: A Playwright suite whose app does not exist yet must drive the fix loop until the browser assertion passes
func TestE2E011(t *testing.T) {
	s := scenarios.New(t, "E2E-011")
	s.Given(`the "build-code-playwright-nextjs" project tree`)
	s.And(`the project's browser test dependencies are installed`)
	s.And(`the System Architect answers "1" to every prompt`)
	s.When(`the System Architect runs "build code --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches msg="Running tests" suite=frontend/integration framework=playwright`)
	s.And(`stdout matches BUILD CODE COMPLETE`)
	s.And(`the file "services/frontend/Dockerfile" is created`)
	s.And(`the file "services/frontend/package.json" is created`)
	s.But(`the file "docker-compose.yaml" is unchanged`)
	s.And(`the file "tests/integration/frontend-home.spec.ts" is unchanged`)
	s.And(`the file "docs/architecture/architecture.yaml" is unchanged`)
	s.And(`no file outside "tmp" and "services/frontend" changed`)
	s.And(`the command "npx playwright test --reporter=json --config playwright.config.ts integration" run in "tests" exits with code 0`)
	s.And(`judge: services/frontend/package.json declares Next.js and React, and defines whichever of the dev or start scripts the created Dockerfile invokes to launch the server`)
	s.And(`judge: services/frontend/Dockerfile defines a runnable Next.js build — it installs the declared dependencies, exposes the port docker-compose.yaml maps, and starts the server`)
	s.Done()
}

// E2E-012: A framework the engine cannot route to must be refused, not walked
func TestE2E012(t *testing.T) {
	s := scenarios.New(t, "E2E-012")
	s.Given(`the "build-code-unknown-framework" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches unknown test framework`)
	s.And(`stdout matches rspec`)
	s.And(`stdout matches calc/e2e`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-013: A suite whose `service:` names no declared service must be refused
func TestE2E013(t *testing.T) {
	s := scenarios.New(t, "E2E-013")
	s.Given(`the "build-code-unknown-suite-service" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches architecture\.testing\.suites\[e2e\]`)
	s.And(`stdout matches service \\"calulator\\"`)
	s.And(`stdout matches names a service the architecture does not declare`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-014: A command whose quoting never closes must be refused, not guessed
func TestE2E014(t *testing.T) {
	s := scenarios.New(t, "E2E-014")
	s.Given(`the "build-code-unterminated-quote" project tree`)
	s.When(`the System Architect runs "build code"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start`)
	s.And(`stdout matches unterminated quote`)
	s.And(`stdout matches calc/e2e`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the engine spawned no test runner`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}
