//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-020: --help must print the command tree and change nothing on disk
func TestE2E020(t *testing.T) {
	s := scenarios.New(t, "E2E-020")
	s.Given(`the "help-flag" project tree`)
	s.When(`the System Architect runs "--help"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches TrueBDD CLI`)
	s.And(`stdout matches Usage:`)
	s.And(`stdout matches true-bdd \[command\]`)
	s.And(`stdout matches Available Commands:`)
	s.And(`stdout matches \bbuild\b`)
	s.And(`stdout matches \bus\b`)
	s.And(`stdout matches -h, --help`)
	s.And(`no file outside "tmp" changed`)
	s.Done()
}
