//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-291: A registry scenario that satisfies every walked prompt must pass the walk and report success
func TestE2E291(t *testing.T) {
	s := scenarios.New(t, "E2E-291")
	s.Given(`the "scen-check-happy-path" project tree`)
	s.When(`the System Architect runs "scen check"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches SCEN CHECK`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches SCEN CHECK COMPLETE`)
	s.And(`the engine dispatched 8 AI turns`)
	s.And(`no file outside "tmp" changed`)
	s.Done()
}

// E2E-292: A registry scenario that fails a walked prompt must be reported as failed and still exit 0, because the command is advisory
func TestE2E292(t *testing.T) {
	s := scenarios.New(t, "E2E-292")
	s.Given(`the "scen-check-validation-fails" project tree`)
	s.When(`the System Architect runs "scen check"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches SCEN CHECK`)
	s.And(`stdout matches Validation failed`)
	s.But(`stdout does not match ALL CHECKS PASSED`)
	s.And(`the engine dispatched 8 AI turns`)
	s.And(`no file outside "tmp" changed`)
	s.Done()
}

// E2E-293: A --fix run must be refused before the walk, because the scen-check checklist ships no fix template for any prompt
func TestE2E293(t *testing.T) {
	s := scenarios.New(t, "E2E-293")
	s.Given(`the "scen-check-fix-refused" project tree`)
	s.When(`the System Architect runs "scen check --fix"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="scen check"`)
	s.But(`stdout does not match SCEN CHECK`)
	s.And(`no file outside "tmp" changed`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-294: An id naming no scenario in the registry must be refused before the first prompt, never walked as an empty selection
func TestE2E294(t *testing.T) {
	s := scenarios.New(t, "E2E-294")
	s.Given(`the "scen-check-unknown-id" project tree`)
	s.When(`the System Architect runs "scen check E2E-999"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches SCEN CHECK`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="scen check"`)
	s.And(`no file outside "tmp" changed`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-295: A registry that parses but holds no scenarios must be refused, so the walk never reports success over nothing
func TestE2E295(t *testing.T) {
	s := scenarios.New(t, "E2E-295")
	s.Given(`the "scen-check-empty-registry" project tree`)
	s.When(`the System Architect runs "scen check"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches SCEN CHECK`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="scen check"`)
	s.And(`no file outside "tmp" changed`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-296: Ids given on the command line must narrow the walk to exactly those scenarios, in ascending id order whatever order they were typed
func TestE2E296(t *testing.T) {
	s := scenarios.New(t, "E2E-296")
	s.Given(`the "scen-check-id-filter" project tree`)
	s.And(`the "scen-check" checklist is narrowed to its "whether this scenario's description follows the rule-based format" prompt`)
	s.When(`the System Architect runs "scen check E2E-002 E2E-001"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches SCEN CHECK`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`the engine dispatched 2 AI turns`)
	s.But(`stdout does not match E2E-003`)
	s.And(`no file outside "tmp" changed`)
	s.Done()
}
