//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-021: Two registry entries claiming the same acceptance criterion must collapse into one, leaving every other entry untouched
func TestE2E021(t *testing.T) {
	s := scenarios.New(t, "E2E-021")
	s.Given(`the "us-apply-duplicate-collapse" project tree`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us apply 95.1 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches AC 1/1:`)
	s.And(`stdout matches RE-WALK 2/`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches APPLY COMPLETE`)
	s.And(`the file "docs/scenarios.yaml" is modified`)
	s.And(`exactly 1 scenario in "docs/scenarios.yaml" comes from acceptance criterion "95.1-001"`)
	s.And(`the scenario from acceptance criterion "95.1-001" in "docs/scenarios.yaml" cites the story "docs/product/stories/95.1-duplicate-collapse.yaml"`)
	s.And(`the scenario from acceptance criterion "95.1-001" in "docs/scenarios.yaml" matches HTTP 200`)
	s.And(`exactly 1 scenario in "docs/scenarios.yaml" comes from acceptance criterion "90.1-001"`)
	s.But(`the file "docs/product/stories/95.1-duplicate-collapse.yaml" is unchanged`)
	s.And(`the only file changed outside "tmp" is "docs/scenarios.yaml"`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: the scenario from acceptance criterion 90.1-001 — the unrelated home-page welcome banner — still says what the seed registry said it did`)
	s.Done()
}

// E2E-022: A story carried forward from the older `scenarios.test_scenarios[]` layout must be refused, and told what to convert
func TestE2E022(t *testing.T) {
	s := scenarios.New(t, "E2E-022")
	s.Given(`the "us-apply-malformed-scenarios" project tree`)
	s.When(`the Product Owner runs "us apply 95.5"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US APPLY — Story 95\.5`)
	s.And(`stdout matches msg="Seeded scratch registry"`)
	s.And(`stdout matches Cannot start: .*story uses deprecated scenarios\.test_scenarios format`)
	s.And(`stdout matches us apply requires acceptance_criteria with embedded steps`)
	s.And(`stdout matches docs/product/stories/95\.5-legacy-test-scenarios\.yaml`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us apply"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the file "docs/product/stories/95.5-legacy-test-scenarios.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-023: `us apply` on a story number that has no file must be refused, and the refusal must say what filename it looked for
func TestE2E023(t *testing.T) {
	s := scenarios.New(t, "E2E-023")
	s.Given(`the "us-apply-missing-story" project tree`)
	s.When(`the Product Owner runs "us apply 95.4"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US APPLY — Story 95\.4`)
	s.And(`stdout matches msg="Seeded scratch registry"`)
	s.And(`stdout matches Cannot start: .*no story file found for story 95\.4`)
	s.And(`stdout matches in docs/product/stories \(expected format: 95\.4-<slug>\.yaml\)`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us apply"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the file "docs/product/stories/95.1-duplicate-collapse.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-024: Every location a host project uses is supposed to come from `true-bdd.yaml` — never a hardcoded path
func TestE2E024(t *testing.T) {
	s := scenarios.New(t, "E2E-024")
	s.Given(`the "us-apply-relocated-registry" project tree`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us apply 95.2 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches AC 1/1:`)
	s.And(`stdout matches RE-WALK 2/`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches APPLY COMPLETE`)
	s.And(`stdout matches docs/specs/requirements\.yaml updated from scratch`)
	s.And(`the file "docs/specs/requirements.yaml" is modified`)
	s.And(`exactly 1 scenario in "docs/specs/requirements.yaml" comes from acceptance criterion "95.2-001"`)
	s.And(`the scenario from acceptance criterion "95.2-001" in "docs/specs/requirements.yaml" cites the story "docs/product/stories/95.2-relocated-registry.yaml"`)
	s.And(`the scenario from acceptance criterion "95.2-001" in "docs/specs/requirements.yaml" matches /health`)
	s.And(`exactly 1 scenario in "docs/specs/requirements.yaml" comes from acceptance criterion "90.2-001"`)
	s.But(`no file matching "docs/scenarios.yaml" is created`)
	s.And(`the file "docs/product/stories/95.2-relocated-registry.yaml" is unchanged`)
	s.And(`judge: the scenario from acceptance criterion 90.2-001 — the unrelated settings page — still says what the seed registry said it did`)
	s.Done()
}

// E2E-025: A story whose acceptance criteria are all missing from the registry must re-walk after the merge and end at a fixpoint
func TestE2E025(t *testing.T) {
	s := scenarios.New(t, "E2E-025")
	s.Given(`the "us-apply-rewalk-converges" project tree`)
	s.And(`the "us-apply" checklist is narrowed to its "already appear as a scenario in the registry" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us apply 99.3 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches AC 1/2:`)
	s.And(`stdout matches AC 2/2:`)
	s.And(`stdout matches RE-WALK 2/`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches APPLY COMPLETE`)
	s.And(`the file "docs/scenarios.yaml" is modified`)
	s.And(`exactly 1 scenario in "docs/scenarios.yaml" comes from acceptance criterion "99.3-001"`)
	s.And(`exactly 1 scenario in "docs/scenarios.yaml" comes from acceptance criterion "99.3-002"`)
	s.And(`no two scenarios in "docs/scenarios.yaml" share the same steps`)
	s.But(`the file "docs/product/stories/99.3-rewalk-fixture.yaml" is unchanged`)
	s.And(`the only file changed outside "tmp" is "docs/scenarios.yaml"`)
	s.And(`stdout does not match RE-WALK 3/`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: each scenario added to the registry carries the given, when and then steps of the acceptance criterion it came from in docs/product/stories/99.3-rewalk-fixture.yaml`)
	s.Done()
}

// E2E-026: `us apply` on a story that was created but never refined must be refused, not walked to a trivial success
func TestE2E026(t *testing.T) {
	s := scenarios.New(t, "E2E-026")
	s.Given(`the "us-apply-story-without-acs" project tree`)
	s.When(`the Product Owner runs "us apply 95.3"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US APPLY — Story 95\.3`)
	s.And(`stdout matches msg="Seeded scratch registry"`)
	s.And(`stdout matches Cannot start: .*story has no acceptance_criteria entries to apply`)
	s.And(`stdout matches docs/product/stories/95\.3-document-summary-created-not-refined\.yaml: story has no acceptance_criteria entries to apply`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us apply"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/scenarios.yaml" is unchanged`)
	s.And(`the file "docs/product/stories/95.3-document-summary-created-not-refined.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}
