//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-027: Two files claiming the same epic number must be refused, not silently resolved by taking the first glob match
func TestE2E027(t *testing.T) {
	s := scenarios.New(t, "E2E-027")
	s.Given(`the "us-create-ambiguous-epic" project tree`)
	s.When(`the Product Owner runs "us create 92.1"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US CREATE — Story 92\.1`)
	s.And(`stdout matches Cannot start: failed to load items: failed to load story:`)
	s.And(`stdout matches failed to load epic 92`)
	s.And(`stdout matches multiple epic files found matching pattern docs/product/epics/epic-92-\*\.yaml`)
	s.And(`stdout matches \[docs/product/epics/epic-92-document-intelligence\.yaml docs/product/epics/epic-92-summaries\.yaml\]`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us create"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-028: A story number that is not `<epic>.<story>` must be refused before anything is read
func TestE2E028(t *testing.T) {
	s := scenarios.New(t, "E2E-028")
	s.Given(`the "us-create-bad-story-number" project tree`)
	s.When(`the Product Owner runs "us create 4"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches Cannot start: invalid story number: invalid story number format`)
	s.And(`stdout matches expected <epic>\.<story>, got "4"`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us create"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-029: A `--fix` run must be refused when any prompt it would walk carries no `F:`, rather than spending a fix turn that has nothing to say
func TestE2E029(t *testing.T) {
	s := scenarios.New(t, "E2E-029")
	s.Given(`the "us-create-unfixable-checklist" project tree`)
	s.When(`the Product Owner runs "us create 99.1 --fix"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches Cannot start: checklist has prompts with no F fix template, so --fix has nothing to apply: us-create has 9 of 9`)
	s.And(`stdout matches us-create/format #1 Does the story follow the format`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us create"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-030: A story seed that passes every check must be written to the stories directory as one new file
func TestE2E030(t *testing.T) {
	s := scenarios.New(t, "E2E-030")
	s.Given(`the "us-create-happy-path" project tree`)
	s.When(`the Product Owner runs "us create 99.1"`)
	s.Then(`the command exits with code 0`)
	s.And(`exactly 1 file matching "docs/product/stories/*.yaml" is created`)
	s.And(`exactly 1 file matching "docs/product/stories/99.1-*.yaml" is created`)
	s.And(`the story "docs/product/stories/99.1-*.yaml" has id "99.1"`)
	s.And(`the story "docs/product/stories/99.1-*.yaml" has at least 3 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/99.1-*.yaml" has an id matching ^AC-\d+$ and a non-empty description`)
	s.But(`the file "docs/product/epics/epic-99-bdd-test.yaml" is unchanged`)
	s.And(`no file outside "tmp" and "docs/product/stories" changed`)
	s.And(`judge: the story's as_a, i_want and so_that clauses keep the meaning of the epic's — a Claude User who wants a short summary of a Google Doc on request, so as not to have to download it or copy sections of it into a separate tool just to get a quick gist`)
	s.And(`judge: the acceptance criteria cover the substance of the epic's three — summarising a shared Google Doc, the error path when the document is not shared, and the partial-summary path when it is too long — in any order, with polished wording, and with extra criteria allowed`)
	s.Done()
}

// E2E-031: A story seed with no as_a clause and a generic so_that must fail both checks and write no story file
func TestE2E031(t *testing.T) {
	s := scenarios.New(t, "E2E-031")
	s.Given(`the "us-create-missing-clause" project tree`)
	s.When(`the Product Owner runs "us create 97.1"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches Validation failed. Use --fix flag to enter interactive fix mode.`)
	s.And(`stdout matches CREATE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`stdout does not match ALL CHECKS PASSED!`)
	s.And(`stdout does not match Story saved to:`)
	s.Done()
}

// E2E-032: A checklist prompt may only ask for evidence the engine can actually hand it
func TestE2E032(t *testing.T) {
	s := scenarios.New(t, "E2E-032")
	s.Given(`the "us-create-missing-document" project tree`)
	s.When(`the Product Owner runs "us create 99.1"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches docs/product/product\.yaml`)
	s.And(`stdout matches Cannot start: checklist declares documents that cannot be provided`)
	s.And(`stdout matches level=ERROR msg="Refusing to start: checklist documents unsatisfiable" command="us create" checklist=us-create`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-033: An epic number with no file must be refused, and the refusal must show the filename pattern that found nothing
func TestE2E033(t *testing.T) {
	s := scenarios.New(t, "E2E-033")
	s.Given(`the "us-create-missing-epic" project tree`)
	s.When(`the Product Owner runs "us create 93.1"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US CREATE — Story 93\.1`)
	s.And(`stdout matches Cannot start: failed to load items: failed to load story:`)
	s.And(`stdout matches failed to load epic 93`)
	s.And(`stdout matches no epic file found matching pattern docs/product/epics/epic-93-\*\.yaml`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us create"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the file "docs/product/epics/epic-99-bdd-test.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-034: Asking for a story index the epic does not have must be refused with both numbers in the message
func TestE2E034(t *testing.T) {
	s := scenarios.New(t, "E2E-034")
	s.Given(`the "us-create-story-out-of-range" project tree`)
	s.When(`the Product Owner runs "us create 94.7"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US CREATE — Story 94\.7`)
	s.And(`stdout matches Cannot start: failed to load items: failed to load story:`)
	s.And(`stdout matches story index 7 out of bounds for epic 94 \(has 2 stories\)`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us create"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-035: A story seed defective in every checked dimension must report each failure and write no story file
func TestE2E035(t *testing.T) {
	s := scenarios.New(t, "E2E-035")
	s.Given(`the "us-create-validation-fails" project tree`)
	s.When(`the Product Owner runs "us create 98.1"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches Validation failed. Use --fix flag to enter interactive fix mode.`)
	s.And(`stdout matches CREATE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`no file matching "docs/product/stories/*.yaml" is created`)
	s.And(`stdout does not match ALL CHECKS PASSED!`)
	s.And(`stdout does not match Story saved to:`)
	s.Done()
}
