//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddcli_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-cli/scenarios"
)

// E2E-036: Two files claiming the same story id must be refused, not silently resolved by picking one
func TestE2E036(t *testing.T) {
	s := scenarios.New(t, "E2E-036")
	s.Given(`the "us-refine-ambiguous-story" project tree`)
	s.When(`the Product Owner runs "us refine 96.9"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US REFINE — Story 96\.9`)
	s.And(`stdout matches level=ERROR msg="Multiple story files found" story_number=96\.9 count=2`)
	s.And(`stdout matches multiple story files found for story 96\.9`)
	s.And(`stdout matches 96\.9-document-summary\.yaml`)
	s.And(`stdout matches 96\.9-document-summary-v2\.yaml`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us refine"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/product/stories/96.9-document-summary.yaml" is unchanged`)
	s.And(`the file "docs/product/stories/96.9-document-summary-v2.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-037: A vague qualifier in an acceptance criterion's description must drive the fix loop until the description is measurable
func TestE2E037(t *testing.T) {
	s := scenarios.New(t, "E2E-037")
	s.Given(`the "us-refine-fix-desc-qualifier" project tree`)
	s.And(`the "us-refine" checklist is narrowed to its "whether its description field contains a vague word" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us refine 96.6 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.6-document-summary-desc-qualifier.yaml"`)
	s.And(`the story "docs/product/stories/96.6-document-summary-desc-qualifier.yaml" has id "96.6"`)
	s.And(`the story "docs/product/stories/96.6-document-summary-desc-qualifier.yaml" has 4 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.6-document-summary-desc-qualifier.yaml" has given, when and then steps`)
	s.And(`the description of acceptance criterion "AC-3" of the story "docs/product/stories/96.6-document-summary-desc-qualifier.yaml" does not match (?i)\b(properly|correctly|appropriate|user-friendly|fast|quickly|easily|seamless|intuitive)\b`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: the four acceptance criteria still cover the substance of the seed — a 150-word summary, the unshared-document message, the timeout message, and the first-10000-words notice — with every exact message and numeric threshold intact`)
	s.Done()
}

// E2E-038: An acceptance criterion described in Given/When/Then prose must drive the fix loop until it states a rule
func TestE2E038(t *testing.T) {
	s := scenarios.New(t, "E2E-038")
	s.Given(`the "us-refine-fix-descriptions" project tree`)
	s.And(`the "us-refine" checklist is narrowed to its "whether its description field follows the rule-based format" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us refine 96.2 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.2-document-summary-descriptions.yaml"`)
	s.And(`the story "docs/product/stories/96.2-document-summary-descriptions.yaml" has id "96.2"`)
	s.And(`the story "docs/product/stories/96.2-document-summary-descriptions.yaml" has 5 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.2-document-summary-descriptions.yaml" has given, when and then steps`)
	s.And(`the description of acceptance criterion "AC-1" of the story "docs/product/stories/96.2-document-summary-descriptions.yaml" matches (?i)\b(must|should)\b`)
	s.And(`the description of acceptance criterion "AC-1" of the story "docs/product/stories/96.2-document-summary-descriptions.yaml" does not match (?i)\bwhen\b.*\bthen\b`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: the five acceptance criteria still cover the substance of the seed — a 150-word summary, the unshared-document message, the timeout message, the first-10000-words notice, and the section-heading outline — with every exact message and numeric threshold intact`)
	s.Done()
}

// E2E-039: A forbidden action verb in a step must drive the fix loop until the step names an observable action
func TestE2E039(t *testing.T) {
	s := scenarios.New(t, "E2E-039")
	s.Given(`the "us-refine-fix-forbidden-verb" project tree`)
	s.And(`the "us-refine" checklist is narrowed to its "use action verbs from the forbidden_actions list" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us refine 96.8 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.8-document-summary-forbidden-verb.yaml"`)
	s.And(`the story "docs/product/stories/96.8-document-summary-forbidden-verb.yaml" has id "96.8"`)
	s.And(`the story "docs/product/stories/96.8-document-summary-forbidden-verb.yaml" has 4 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.8-document-summary-forbidden-verb.yaml" has given, when and then steps`)
	s.And(`the steps of acceptance criterion "AC-1" of the story "docs/product/stories/96.8-document-summary-forbidden-verb.yaml" do not match (?i)\b(handle|handles|process|parse)\b`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: AC-1's then step now states a concrete observable action in place of the forbidden verb, and keeps the 150-word threshold; the four criteria still cover the substance of the seed with every exact message intact`)
	s.Done()
}

// E2E-040: A vague qualifier in a step must drive the fix loop until the step is measurable
func TestE2E040(t *testing.T) {
	s := scenarios.New(t, "E2E-040")
	s.Given(`the "us-refine-fix-step-qualifier" project tree`)
	s.And(`the "us-refine" checklist is narrowed to its "whether its steps field contains a vague word" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us refine 96.7 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.7-document-summary-step-qualifier.yaml"`)
	s.And(`the story "docs/product/stories/96.7-document-summary-step-qualifier.yaml" has id "96.7"`)
	s.And(`the story "docs/product/stories/96.7-document-summary-step-qualifier.yaml" has 4 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.7-document-summary-step-qualifier.yaml" has given, when and then steps`)
	s.And(`the steps of acceptance criterion "AC-4" of the story "docs/product/stories/96.7-document-summary-step-qualifier.yaml" do not match (?i)\b(properly|correctly|appropriate|user-friendly|fast|quickly|easily|seamless|intuitive)\b`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: AC-4's then step still states the first-10000-words notice as an observable outcome, and the four criteria still cover the substance of the seed with every exact message and numeric threshold intact`)
	s.Done()
}

// E2E-041: An acceptance criterion with no steps must drive the fix loop until it carries Given/When/Then
func TestE2E041(t *testing.T) {
	s := scenarios.New(t, "E2E-041")
	s.Given(`the "us-refine-fix-steps" project tree`)
	s.And(`the "us-refine" checklist is narrowed to its "whether its steps field follows the Given/When/Then format" prompt`)
	s.And(`the Product Owner answers "1" to every prompt`)
	s.When(`the Product Owner runs "us refine 96.5 --fix"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.5-document-summary-steps.yaml"`)
	s.And(`the story "docs/product/stories/96.5-document-summary-steps.yaml" has id "96.5"`)
	s.And(`the story "docs/product/stories/96.5-document-summary-steps.yaml" has 5 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.5-document-summary-steps.yaml" has given, when and then steps`)
	s.And(`stdout does not match Hit max apply attempts`)
	s.And(`judge: AC-2's new given, when and then steps are derived from its own description, and the five criteria still cover the substance of the seed with every exact message and numeric threshold intact`)
	s.Done()
}

// E2E-042: A story whose acceptance criteria already pass every check must converge on the first walk and be rewritten in place
func TestE2E042(t *testing.T) {
	s := scenarios.New(t, "E2E-042")
	s.Given(`the "us-refine-happy-path" project tree`)
	s.When(`the Product Owner runs "us refine 96.1"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches ALL CHECKS PASSED!`)
	s.And(`stdout matches msg="Story saved"`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.And(`the only file changed outside "tmp" is "docs/product/stories/96.1-document-summary-refined.yaml"`)
	s.And(`the story "docs/product/stories/96.1-document-summary-refined.yaml" has id "96.1"`)
	s.And(`the story "docs/product/stories/96.1-document-summary-refined.yaml" has 4 acceptance criteria`)
	s.And(`every acceptance criterion in the story "docs/product/stories/96.1-document-summary-refined.yaml" has given, when and then steps`)
	s.And(`judge: the four acceptance criteria still cover the substance of the seed — a summary of 150 words or fewer for a shared document, the "This document is not shared with your account" message, the "The summary timed out - please try again" message at 30 seconds, and summarising only the first 10000 words — with every exact message and number intact`)
	s.And(`judge: the as_a, i_want and so_that clauses keep their meaning — a Claude User wanting a short summary of a shared Google Doc on request, so as to decide whether it needs attention without reading it in full`)
	s.Done()
}

// E2E-043: A story file that is not valid YAML must be refused with the parser's own complaint, not a generic failure
func TestE2E043(t *testing.T) {
	s := scenarios.New(t, "E2E-043")
	s.Given(`the "us-refine-malformed-story" project tree`)
	s.When(`the Product Owner runs "us refine 96.9"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US REFINE — Story 96\.9`)
	s.And(`stdout matches level=ERROR msg="Failed to unmarshal story YAML" file=docs/product/stories/96\.9-document-summary\.yaml`)
	s.And(`stdout matches failed to parse story YAML from docs/product/stories/96\.9-document-summary\.yaml`)
	s.And(`stdout matches mapping values are not allowed in this context`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us refine"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/product/stories/96.9-document-summary.yaml" is unchanged`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-044: `us refine` on a story that was never created must be refused, and the refusal must tell the user which command makes the file
func TestE2E044(t *testing.T) {
	s := scenarios.New(t, "E2E-044")
	s.Given(`the "us-refine-missing-story" project tree`)
	s.When(`the Product Owner runs "us refine 96.9"`)
	s.Then(`the command exits with code 1`)
	s.And(`stdout matches US REFINE — Story 96\.9`)
	s.And(`stdout matches level=ERROR msg="No story file found" story_number=96\.9 pattern=docs/product/stories/96\.9-\*\.yaml`)
	s.And(`stdout matches no story file found for story 96\.9 in docs/product/stories`)
	s.And(`stdout matches \(expected format: 96\.9-<slug>\.yaml\)`)
	s.And(`stdout matches level=ERROR msg="Refusing to start" command="us refine"`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/product/stories/96.1-document-summary-refined.yaml" is unchanged`)
	s.And(`no file matching "docs/product/stories/96.9-*.yaml" is created`)
	s.And(`the engine dispatched no AI turns`)
	s.Done()
}

// E2E-045: A story whose acceptance criteria are all error scenarios must fail the happy-path check and pass the rest
func TestE2E045(t *testing.T) {
	s := scenarios.New(t, "E2E-045")
	s.Given(`the "us-refine-no-happy-path" project tree`)
	s.When(`the Product Owner runs "us refine 96.4"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches Validation failed. Use --fix flag to enter interactive fix mode.`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/product/stories/96.4-summary-error-messages.yaml" is unchanged`)
	s.And(`stdout does not match ALL CHECKS PASSED!`)
	s.And(`stdout does not match Story saved to:`)
	s.Done()
}

// E2E-046: A story with implementation-level and subjective acceptance criteria must report each failure and leave the story unchanged
func TestE2E046(t *testing.T) {
	s := scenarios.New(t, "E2E-046")
	s.Given(`the "us-refine-validation-fails" project tree`)
	s.When(`the Product Owner runs "us refine 96.3"`)
	s.Then(`the command exits with code 0`)
	s.And(`stdout matches Validation failed. Use --fix flag to enter interactive fix mode.`)
	s.And(`stdout matches REFINE COMPLETE`)
	s.But(`no file outside "tmp" changed`)
	s.And(`the file "docs/product/stories/96.3-summary-service-internals.yaml" is unchanged`)
	s.And(`stdout does not match ALL CHECKS PASSED!`)
	s.And(`stdout does not match Story saved to:`)
	s.Done()
}
