//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddweb_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-web/scenarios"
)

// E2E-278: A refine prompt reaches the browser, exiting from it ends the run as a user exit, and the session is usable straight after
func TestE2E278(t *testing.T) {
	s := scenarios.New(t, "E2E-278")
	s.Given(`the "ai-refine-one-defect" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner chooses "exit" on the prompt of run "R1"`)
	s.Then(`run-output is non-empty`)
	s.And(`prompt-dialog has attribute "kind" = "choice"`)
	s.And(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "user_exit"`)
	s.And(`run "R1" recorded events beyond the ones it had at the prompt`)
	s.And(`run-outcome has text "user_exit"`)
	s.And(`the remote spawned at most 6 AI calls`)
	s.And(`no file in the project tree changed`)
	s.And(`the session is listed`)
	s.And(`the session has no active run`)
	s.Done()
}

// E2E-279: The Create action sends the row's position-derived id and the engine writes the one story its declared id names
func TestE2E279(t *testing.T) {
	s := scenarios.New(t, "E2E-279")
	s.Given(`the "a1-create-no-fix" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`the Product Owner has the session page of "A" open`)
	s.When(`the Product Owner clicks story-row[create-id=42.1] > action-create`)
	s.Then(`story-row[create-id=42.1] > fix-toggle was not checked`)
	s.And(`the dispatched run has command "us-create"`)
	s.And(`the dispatched run has story "42.1"`)
	s.And(`the dispatched run has fix unset`)
	s.And(`the dispatched run reaches a terminal state`)
	s.And(`the dispatched run has outcome "converged"`)
	s.And(`exactly 1 file matching "docs/product/stories/77.5-*.yaml" is created`)
	s.And(`the remote spawned at most 5 AI calls`)
	s.And(`story-row[create-id=42.1] > story-created has attribute "status" = "one"`)
	s.Done()
}

// E2E-280: A story one CLI created is seen by every live CLI on the same folder, because each read is a fresh scan of one shared store
func TestE2E280(t *testing.T) {
	s := scenarios.New(t, "E2E-280")
	s.Given(`the "a1-create-no-fix" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner has the session page of "A" open`)
	s.And(`the Product Owner has created story "42.1" through its row`)
	s.When(`the Product Owner opens the session page of "B"`)
	s.Then(`story-row[create-id=42.1] > story-created has attribute "status" = "one"`)
	s.Done()
}

// E2E-281: The refine fix loop answers a choice, takes multiline feedback, comes back with a second distinct choice, and applies until the designed defect is gone
func TestE2E281(t *testing.T) {
	s := scenarios.New(t, "E2E-281")
	s.Given(`the "a2-refine-fix-loop" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner checks story-row[create-id=70.1] > fix-toggle`)
	s.And(`the Product Owner clicks story-row[create-id=70.1] > action-refine`)
	s.And(`the Product Owner opens the run page for the dispatched run`)
	s.And(`the Product Owner chooses "refine" on the prompt of the dispatched run`)
	s.And(`the Product Owner submits two lines of refinement feedback with no trailing blank line`)
	s.And(`the Product Owner applies each choice prompt of the dispatched run, at most 5 times`)
	s.Then(`the dispatched run has command "us-refine"`)
	s.And(`the dispatched run has story "77.5"`)
	s.And(`the dispatched run has fix set`)
	s.And(`the second choice prompt carries an id different from the first and from the freetext one`)
	s.And(`the dispatched run was applied at least once`)
	s.And(`the dispatched run has outcome "converged"`)
	s.And(`run-outcome has text "converged"`)
	s.And(`the dispatched run's prompts began "choice", "freetext", "choice"`)
	s.And(`the remote spawned at most 12 AI calls`)
	s.And(`the only files changed match "docs/product/stories/77.5-*.yaml"`)
	s.And(`the description of acceptance criterion "AC-1" of "docs/product/stories/77.5-document-summary.yaml" matches (?i)\b(must|should)\b`)
	s.But(`the description of acceptance criterion "AC-1" of "docs/product/stories/77.5-document-summary.yaml" does not match (?i)\b(given|then)\b`)
	s.And(`judge: the rewritten AC-1 still requires the behaviour the seed described — a summary of at most 150 words — stated as a rule rather than as steps`)
	s.Done()
}

// E2E-282: Duplicate acceptance criteria make the fix generator ask before merging, and answering by number records the option that number named
func TestE2E282(t *testing.T) {
	s := scenarios.New(t, "E2E-282")
	s.Given(`the "a3-clarify" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "us-refine" for story "44.1" with fix as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.And(`run "R1" publishes a "clarify" prompt`)
	s.When(`the Product Owner submits "1" to the clarify prompt of run "R1"`)
	s.Then(`prompt-clarify-option[index=1] is non-empty`)
	s.And(`run-output contains the text of prompt-clarify-option[index=1]`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.And(`choosing "exit" on the prompt of run "R1" ends it with outcome "user_exit"`)
	s.And(`the remote spawned at most 8 AI calls`)
	s.And(`no file in the project tree changed`)
	s.Done()
}

// E2E-283: The Apply action merges the story's acceptance criterion into the registry under its own lineage, leaving every entry already there untouched
func TestE2E283(t *testing.T) {
	s := scenarios.New(t, "E2E-283")
	s.Given(`the "a4-apply-fix" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner checks story-row[create-id=70.1] > fix-toggle`)
	s.And(`the Product Owner clicks story-row[create-id=70.1] > action-apply`)
	s.And(`the Product Owner opens the run page for the dispatched run`)
	s.And(`the Product Owner applies each choice prompt of the dispatched run, at most 5 times`)
	s.Then(`the dispatched run has command "us-apply"`)
	s.And(`the dispatched run has story "77.5"`)
	s.And(`the dispatched run has fix set`)
	s.And(`the dispatched run was applied at least once`)
	s.And(`the dispatched run has outcome "converged"`)
	s.And(`the remote spawned at most 10 AI calls`)
	s.And(`the only file changed is "docs/scenarios.yaml"`)
	s.And(`the scenario "E2E-500" in "docs/scenarios.yaml" is unchanged byte for byte`)
	s.And(`the file "docs/scenarios.yaml" matches 88\.9-001`)
	s.And(`the file "docs/scenarios.yaml" matches docs/product/stories/77\.5-apply-summary\.yaml`)
	s.And(`the file "docs/scenarios.yaml" matches a summary of 150 words or fewer`)
	s.Done()
}

// E2E-284: A registry entry no test runs drives the fix loop to author one under the test root, naming the scenario it covers
func TestE2E284(t *testing.T) {
	s := scenarios.New(t, "E2E-284")
	s.Given(`the "a5-build-tests-fix" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "build-tests" with fix as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.When(`the Product Owner applies each choice prompt of run "R1", at most 5 times`)
	s.Then(`run "R1" was applied at least once`)
	s.And(`run "R1" has outcome "converged"`)
	s.And(`the remote spawned at most 10 AI calls`)
	s.And(`the only files changed match "tests/**"`)
	s.And(`at least 1 file matching "tests/**" is created`)
	s.And(`no file was modified`)
	s.And(`the created test matches INT-901`)
	s.And(`the created test matches \b(test\(|describe\(|it\(|func Test)`)
	s.Done()
}

// E2E-285: A failing test drives the fix loop to change production source until it passes, and nothing outside the service is touched
func TestE2E285(t *testing.T) {
	s := scenarios.New(t, "E2E-285")
	s.Given(`the "a6-build-code-fix" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "build-code" with fix as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.When(`the Product Owner applies each choice prompt of run "R1", at most 5 times`)
	s.Then(`run "R1" was applied at least once`)
	s.And(`run "R1" has outcome "converged"`)
	s.And(`the remote spawned at most 12 AI calls`)
	s.And(`the only files changed match "services/**"`)
	s.And(`the file "services/calculator/calc.go" is modified`)
	s.And(`the file "services/calculator/calc_test.go" is unchanged`)
	s.And(`the file "docs/architecture/architecture.yaml" is unchanged`)
	s.And(`the project's own tests pass when run directly`)
	s.Done()
}

// E2E-286: A folder already in use warns its sibling and refuses that sibling's command fast, because the lock decides and not the relay
func TestE2E286(t *testing.T) {
	s := scenarios.New(t, "E2E-286")
	s.Given(`the "ai-refine-one-defect" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner opens the session page of "B"`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix on session "B" as run "R2"`)
	s.Then(`the page shows folder-warning-banner`)
	s.And(`run "R2" reaches a terminal state`)
	s.And(`run "R2" has outcome "error"`)
	s.And(`run "R2" has error detail "folder_locked"`)
	s.And(`no file in the project tree changed`)
	s.Done()
}

// E2E-287: A replacement CLI reconciles the run a killed holder left behind, ending it as abandoned
func TestE2E287(t *testing.T) {
	s := scenarios.New(t, "E2E-287")
	s.Given(`the "ai-refine-one-defect" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`remote "A" is stopped with "SIGKILL"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.Then(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "abandoned"`)
	s.And(`the remote spawned at most 6 AI calls`)
	s.And(`no file in the project tree changed`)
	s.Done()
}

// E2E-288: A relay restart while the CLI and its child live on leaves the pending prompt readable, and the answer resubmitted after it is consumed exactly once by the same child
func TestE2E288(t *testing.T) {
	s := scenarios.New(t, "E2E-288")
	s.Given(`the "ai-refine-one-defect" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the relay restarts`)
	s.And(`the Product Owner answers the pending prompt of run "R1" with "exit"`)
	s.Then(`the session is listed`)
	s.And(`run "R1" still waited on the same prompt after the restart`)
	s.And(`the answer returned status 200`)
	s.And(`the run's command child is the same process group it was before`)
	s.And(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "user_exit"`)
	s.And(`run "R1"'s event sequence numbers are unique`)
	s.And(`every sequence number recorded before the restart appears exactly once`)
	s.And(`run "R1" published exactly 1 prompt`)
	s.And(`the remote spawned at most 6 AI calls`)
	s.And(`no file in the project tree changed`)
	s.Done()
}

// E2E-289: An interrupt during a real model call ends the run as interrupted with no descendant left running, and a replacement CLI reads that ending and reuses the folder
func TestE2E289(t *testing.T) {
	s := scenarios.New(t, "E2E-289")
	s.Given(`the "ai-refine-one-defect" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "us-refine" for story "30.1" with fix as run "R1"`)
	s.And(`the remote has a live agent descendant`)
	s.When(`the remote's process group is sent "SIGINT"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.Then(`the remote exited`)
	s.And(`no agent descendant of the remote survives`)
	s.And(`the remote spawned at most 8 AI calls`)
	s.And(`no file in the project tree changed`)
	s.And(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "interrupted"`)
	s.And(`the project history holds run "R1"`)
	s.And(`dispatching "version" on session "B" reaches a terminal state with outcome "ok"`)
	s.Done()
}

// E2E-290: A real model turn asked through the workspace chat edits the document and the CLI persists it, along the same path a typed edit takes
func TestE2E290(t *testing.T) {
	s := scenarios.New(t, "E2E-290")
	s.Given(`the workspace is connected with a real model driving the chat`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner asks the chat in prose to add a uniquely-named term`)
	s.Then(`file-view-editor contains the new term`)
	s.And(`"docs/architecture/architecture.yaml" holds the new term under its "terms" node`)
	s.And(`the browser's write receipt names that path and the file's hash`)
	s.And(`the relay's audit holds the CLI's receipt for the same work, revision and hash`)
	s.And(`the remote spawned at most 3 AI calls`)
	s.Done()
}
