//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddweb_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-web/scenarios"
)

// E2E-222: A design token is what the chrome is actually painted from, so changing the token at the root repaints it
func TestE2E222(t *testing.T) {
	s := scenarios.New(t, "E2E-222")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`rail resolves "background-color" from the token "--surface-inverse"`)
	s.And(`rail tracks the token "--surface-inverse" when it is changed`)
	s.Done()
}

// E2E-223: A sidebar group's caret shows the direction it will move in, and an indentation guide marks what is nested under it
func TestE2E223(t *testing.T) {
	s := scenarios.New(t, "E2E-223")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1920x1080`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers sidebar-group[group=Stories]`)
	s.Then(`sidebar-group[group=Stories] > sidebar-caret has text "▾"`)
	s.And(`clicking it changes its glyph to "▸"`)
	s.And(`the page shows sidebar-group[group=Stories] > sidebar-guide-line`)
	s.Done()
}

// E2E-224: The rail's utilities are pinned at its foot and its preview floats clear of it, so neither covers what the reader is using
func TestE2E224(t *testing.T) {
	s := scenarios.New(t, "E2E-224")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1920x1080`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers rail-item[section=architecture]`)
	s.Then(`rail-utilities sits in the lower part of rail`)
	s.And(`rail-flyout begins at or after the right edge of rail`)
	s.Done()
}

// E2E-225: The chat opens with its own header and its input at the foot of the panel, at the width the design gives it
func TestE2E225(t *testing.T) {
	s := scenarios.New(t, "E2E-225")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1920x1080`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page shows chat-dock-header > chat-dock-new`)
	s.And(`chat-dock-input sits in the lower half of chat-dock-panel`)
	s.And(`chat-dock-panel is 380 pixels wide, within 2 pixels`)
	s.Done()
}

// E2E-226: The file view and its gutter are set in a monospaced face while the rest of the page is set in the design face
func TestE2E226(t *testing.T) {
	s := scenarios.New(t, "E2E-226")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`file-view-editor's font family matches mono`)
	s.And(`file-view-gutter's font family matches mono`)
	s.And(`the body's font family matches poppins`)
	s.Done()
}

// E2E-227: The shell owns the height of the window and the content pane owns the scroll, so the chat toggle at the right edge is never under a page scrollbar
func TestE2E227(t *testing.T) {
	s := scenarios.New(t, "E2E-227")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner scrolls content-pane to its end`)
	s.Then(`the document does not scroll`)
	s.And(`clicking chat-dock-toggle shows chat-dock-panel`)
	s.Done()
}

// E2E-228: Every colour a visible element paints comes from the design system's palette
func TestE2E228(t *testing.T) {
	s := scenarios.New(t, "E2E-228")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`every visible element's colours come from the design token palette`)
	s.Done()
}

// E2E-229: Every visible element is set in the design face, the file view's monospace excepted, and that face genuinely renders rather than merely resolving
func TestE2E229(t *testing.T) {
	s := scenarios.New(t, "E2E-229")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`every visible element's type comes from the design token palette`)
	s.And(`the design face actually renders`)
	s.Done()
}

// E2E-230: The chat's own form controls stay inside the palette too, which the closed-chat sweep can never see
func TestE2E230(t *testing.T) {
	s := scenarios.New(t, "E2E-230")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page shows chat-dock-new`)
	s.And(`the page shows chat-dock-input`)
	s.And(`the page shows chat-dock-send`)
	s.And(`every visible element's colours come from the design token palette`)
	s.And(`every visible element's type comes from the design token palette`)
	s.Done()
}

// E2E-231: The canvas padding and the breadcrumb's hairline are drawn at the exact tokens the specification names, not at numbers that happen to match
func TestE2E231(t *testing.T) {
	s := scenarios.New(t, "E2E-231")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`content-pane's padding equals the token "--space-5" on all four sides`)
	s.And(`content-breadcrumb has computed "border-bottom-style" = "solid"`)
	s.And(`content-breadcrumb's bottom border width equals the token "--border-width"`)
	s.And(`content-breadcrumb resolves "border-bottom-color" from the token "--border-hairline"`)
	s.Done()
}

// E2E-232: The workspace frame conforms to the design baseline as a reader sees it
func TestE2E232(t *testing.T) {
	s := scenarios.New(t, "E2E-232")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.Then(`judge: the production frame holds the persistent sidebar, breadcrumb bar and canvas of the baseline, at the baseline's sidebar width, hairline border and canvas padding — ignoring every content and data difference`)
	s.Done()
}

// E2E-233: The workspace overview canvas conforms to the design baseline as a reader sees it
func TestE2E233(t *testing.T) {
	s := scenarios.New(t, "E2E-233")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.And(`every inventory chip has settled onto a live status`)
	s.Then(`judge: the production canvas holds the baseline's title and metadata line, its actions row, its inventory-health list and its breadcrumb trail — tolerating the icon rail and docked sidebar, and ignoring every content and data difference`)
	s.Done()
}

// E2E-234: The product landing conforms to the design baseline as a reader sees it
func TestE2E234(t *testing.T) {
	s := scenarios.New(t, "E2E-234")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`judge: the production page holds the baseline's brand header, icon rail, kicker and title block, file card with its line counter, and its section rows — ignoring every content and data difference`)
	s.Done()
}

// E2E-235: A story page conforms to the design baseline as a reader sees it
func TestE2E235(t *testing.T) {
	s := scenarios.New(t, "E2E-235")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "story 60.1" open`)
	s.Then(`judge: the production page holds the baseline's kicker and title block, its Feature pill and its file card — ignoring every content and data difference`)
	s.Done()
}

// E2E-236: A feature detail page conforms to the design baseline as a reader sees it
func TestE2E236(t *testing.T) {
	s := scenarios.New(t, "E2E-236")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.Then(`judge: the production page holds the baseline's kicker, description and three linked-title sections — ignoring every content and data difference`)
	s.Done()
}

// E2E-237: The sessions home conforms to the design baseline as a reader sees it
func TestE2E237(t *testing.T) {
	s := scenarios.New(t, "E2E-237")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has "/" open`)
	s.Then(`judge: the production page holds the baseline's gradient top bar, wordmark and tagline, its Sessions heading and its row list — tolerating the baseline's test-connection control, and ignoring every content and data difference`)
	s.Done()
}

// E2E-238: The application consumes the workspace density layer rather than numbers that happen to match it
func TestE2E238(t *testing.T) {
	s := scenarios.New(t, "E2E-238")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`the tokens "--wk-fs-row", "--wk-fs-body", "--wk-sidebar-w" and "--wk-rail-w" all resolve`)
	s.And(`feature-row tracks the token "--wk-fs-row" when it is changed`)
	s.And(`sidebar tracks the token "--wk-sidebar-w" when it is changed`)
	s.And(`rail tracks the token "--wk-rail-w" when it is changed`)
	s.Done()
}

// E2E-239: The sidebar's frame and rows are drawn at the density layer's scale, which the editorial body size once quietly overrode
func TestE2E239(t *testing.T) {
	s := scenarios.New(t, "E2E-239")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`sidebar is as wide as the token "--wk-sidebar-w"`)
	s.And(`rail is as wide as the token "--wk-rail-w"`)
	s.And(`feature-row renders at the token "--wk-fs-row"`)
	s.And(`story-row renders at the token "--wk-fs-row"`)
	s.And(`scenario-row renders at the token "--wk-fs-row"`)
	s.And(`new-story-open renders at the token "--wk-fs-row"`)
	s.And(`sidebar-section-header renders at the token "--wk-fs-caption"`)
	s.And(`sidebar-brand-meta renders at the token "--wk-fs-micro"`)
	s.And(`sidebar-brand-meta has computed "text-transform" = "uppercase"`)
	s.Done()
}

// E2E-240: The content chrome is drawn at the dense scale while the display title keeps the editorial one, so neither scale creeps into the other
func TestE2E240(t *testing.T) {
	s := scenarios.New(t, "E2E-240")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`content-breadcrumb renders at the token "--wk-fs-row"`)
	s.And(`content-breadcrumb is as tall as the token "--wk-breadcrumb-h", and no more than 12 pixels taller`)
	s.And(`file-view-kicker renders at the token "--wk-fs-caption"`)
	s.And(`file-view-meta renders at the token "--wk-fs-row"`)
	s.And(`file-view-path renders at the token "--wk-fs-body"`)
	s.And(`file-view-line-count renders at the token "--wk-fs-caption"`)
	s.And(`file-view-title renders at the token "--fs-h3"`)
	s.Done()
}

// E2E-241: The sidebar shows one entry per thing — a single PRD, unruled rows, a guide line that actually paints, and a service annotation on every requirement
func TestE2E241(t *testing.T) {
	s := scenarios.New(t, "E2E-241")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`the sidebar renders exactly 1 "PRD" entry`)
	s.And(`prd-row carries no bottom border rule`)
	s.And(`feature-row carries no bottom border rule`)
	s.And(`story-row carries no bottom border rule`)
	s.And(`scenario-row carries no bottom border rule`)
	s.And(`sidebar-guide-line paints the token "--border-hairline"`)
	s.And(`scenario-row > scenario-row-service is non-empty`)
	s.And(`scenario-row-service renders at the token "--wk-fs-micro"`)
	s.And(`scenario-row-service resolves "color" from the token "--text-muted"`)
	s.Done()
}

// E2E-242: The collapsed chat tab is an inverted vertical strip carrying a word rather than a bare chevron
func TestE2E242(t *testing.T) {
	s := scenarios.New(t, "E2E-242")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`chat-dock-toggle resolves "background-color" from the token "--surface-inverse"`)
	s.And(`chat-dock-toggle resolves "color" from the token "--text-inverse"`)
	s.And(`chat-dock-toggle matches (?i)chat`)
	s.And(`chat-dock-toggle's writing mode is vertical`)
	s.And(`chat-dock-toggle has computed "text-transform" = "uppercase"`)
	s.And(`chat-dock-toggle renders at the token "--wk-fs-caption"`)
	s.Done()
}

// E2E-243: The control that closes the open chat stays a normal button in its header, because the vertical strip belongs to the collapsed tab alone
func TestE2E243(t *testing.T) {
	s := scenarios.New(t, "E2E-243")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the chat's close control's writing mode is horizontal`)
	s.And(`the chat's close control sits inside chat-dock-header`)
	s.Done()
}

// E2E-244: The file card is a dark-outlined box that ends where its content does
func TestE2E244(t *testing.T) {
	s := scenarios.New(t, "E2E-244")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`every edge of the file card draws the token "--border-strong"`)
	s.And(`the file card trails no more than 48 pixels below its last line`)
	s.Done()
}

// E2E-245: The save-state line stays inside the frame, rather than being clipped below the fold
func TestE2E245(t *testing.T) {
	s := scenarios.New(t, "E2E-245")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`the page shows exactly 1 save-state`)
	s.And(`save-state lies wholly inside the viewport`)
	s.Done()
}

// E2E-246: The product breadcrumb is a spaced trail of its own parents ending in a bold current crumb
func TestE2E246(t *testing.T) {
	s := scenarios.New(t, "E2E-246")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`content-breadcrumb holds at least 2 links`)
	s.And(`content-breadcrumb holds at least 2 breadcrumb-sep`)
	s.And(`every breadcrumb-sep has at least 2 pixels of space on both sides`)
	s.And(`content-breadcrumb's current crumb matches (?i)prd\.yaml`)
	s.And(`content-breadcrumb's current crumb resolves "color" from the token "--text-primary"`)
	s.And(`content-breadcrumb's current crumb is bold`)
	s.Done()
}

// E2E-247: No breadcrumb crumb points at the page it is on, because a parent link to the current route is not a parent
func TestE2E247(t *testing.T) {
	s := scenarios.New(t, "E2E-247")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`content-breadcrumb's crumbs read "Sessions", "Workspace overview", "product.yaml"`)
	s.And(`no breadcrumb link points at the current route`)
	s.Done()
}

// E2E-248: The shell is dense by default, so chrome added later inherits the design's scale instead of the editorial one
func TestE2E248(t *testing.T) {
	s := scenarios.New(t, "E2E-248")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`app-shell renders at the token "--wk-fs-body"`)
	s.Done()
}

// E2E-249: A rail entry's icon, label and padding are drawn at the design's own tokens, giving the tile the height it was designed at
func TestE2E249(t *testing.T) {
	s := scenarios.New(t, "E2E-249")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`rail-item-icon renders at the token "--wk-rail-icon-fs"`)
	s.And(`rail-item-label renders at the token "--wk-rail-label-fs"`)
	s.And(`rail-item-label is bold`)
	s.And(`a rail item's vertical padding equals the token "--space-3"`)
	s.Done()
}

// E2E-250: The sidebar's highlight and section bands run edge to edge, because an inset band reads as a different component
func TestE2E250(t *testing.T) {
	s := scenarios.New(t, "E2E-250")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`prd-row's band runs the full width of sidebar`)
	s.And(`sidebar-section-header sits on a band resolving from the token "--surface-subtle"`)
	s.And(`that band runs the full width of sidebar`)
	s.Done()
}

// E2E-251: Every sidebar group label carries the design's trailing colon and its underline
func TestE2E251(t *testing.T) {
	s := scenarios.New(t, "E2E-251")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`every sidebar-group-name ends in a colon`)
	s.And(`every sidebar-group-name is underlined`)
	s.Done()
}

// E2E-252: The new-story control is a quiet affordance rather than a primary one, because adding a story is not the page's main act
func TestE2E252(t *testing.T) {
	s := scenarios.New(t, "E2E-252")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`new-story-open resolves "color" from the token "--text-muted"`)
	s.And(`new-story-open is not bold`)
	s.Done()
}

// E2E-253: The file card's outline is drawn at the design's border width, not at a heavier variant of it
func TestE2E253(t *testing.T) {
	s := scenarios.New(t, "E2E-253")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`every strong edge of the file card is exactly the token "--border-width" thick`)
	s.Done()
}

// E2E-254: The gutter and the editor are padded from the design's spacing tokens, so their text sits where the baseline puts it
func TestE2E254(t *testing.T) {
	s := scenarios.New(t, "E2E-254")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`file-view-gutter's padding equals the token "--space-2" on all four sides`)
	s.And(`file-view-editor's padding equals the token "--space-2" at the top`)
	s.And(`file-view-editor's padding equals the token "--space-3" at the left`)
	s.Done()
}

// E2E-255: Every tree row is boxed at the design's own padding, because matching type sizes at the wrong indent is still the wrong design
func TestE2E255(t *testing.T) {
	s := scenarios.New(t, "E2E-255")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`feature-row is padded "--space-1", "--space-3", "--space-1", "--space-4"`)
	s.And(`story-row is padded "--space-1", "--space-3", "--space-1", "--space-4"`)
	s.And(`scenario-row is padded "--space-1", "--space-3", "--space-1", "--space-4"`)
	s.And(`prd-row renders at the token "--wk-fs-row"`)
	s.Done()
}

// E2E-256: Every piece of workspace chrome matches its captured image, so a drift nobody thought to assert still fails
func TestE2E256(t *testing.T) {
	s := scenarios.New(t, "E2E-256")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`the "rail" matches its golden crop within 1% of its compared pixels`)
	s.And(`the "sidebar" matches its golden crop within 2% of its compared pixels`)
	s.And(`the "breadcrumb" matches its golden crop within 1% of its compared pixels`)
	s.And(`the "file-card" matches its golden crop within 2% of its compared pixels`)
	s.And(`the "chat-toggle" matches its golden crop within 1% of its compared pixels`)
	s.Done()
}

// E2E-257: Live data arriving on the overview moves nothing already on the canvas
func TestE2E257(t *testing.T) {
	s := scenarios.New(t, "E2E-257")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`overview-meta shows the live folder path`)
	s.And(`every inventory chip has settled onto a live status`)
	s.And(`no non-input layout shift moved any overview element`)
	s.Done()
}

// E2E-258: The chat opens at the width the design gives it, keeping the content usable and its resizer to hand
func TestE2E258(t *testing.T) {
	s := scenarios.New(t, "E2E-258")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page shows chat-dock-panel`)
	s.And(`the page shows chat-dock-resizer`)
	s.And(`chat-dock-panel is 380 pixels wide, within 2 pixels`)
	s.And(`content-pane is wider than chat-dock-panel`)
	s.Done()
}

// E2E-259: The rail's preview covers the docked tree exactly, leaving no sliver of what it hides
func TestE2E259(t *testing.T) {
	s := scenarios.New(t, "E2E-259")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner hovers rail-item[section=product]`)
	s.Then(`rail-flyout begins at sidebar's left edge, within 1 pixel`)
	s.And(`rail-flyout is as wide as sidebar, within 1 pixel`)
	s.And(`rail-flyout is at least as tall as sidebar`)
	s.Done()
}

// E2E-260: An architecture document in a shape the outline does not know renders each fixed group with a stated emptiness rather than a bare header
func TestE2E260(t *testing.T) {
	s := scenarios.New(t, "E2E-260")
	s.Given(`the workspace is connected`)
	s.And(`the architecture document is replaced with a valid document holding none of its keys`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`file-view-editor contains the replaced document's marker`)
	s.And(`the page shows exactly 0 yaml-invalid-indicator`)
	s.And(`the page shows exactly 0 arch-service-row`)
	s.And(`the page shows exactly 0 arch-term-row`)
	s.And(`the page shows exactly 0 arch-docker-row`)
	s.And(`every fixed outline group shows a non-empty sidebar-group-empty`)
	s.Done()
}

// E2E-261: A group with entries in it shows no emptiness indicator, because an indicator that always renders indicates nothing
func TestE2E261(t *testing.T) {
	s := scenarios.New(t, "E2E-261")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows sidebar-group[group=Services] > arch-service-row`)
	s.And(`the page shows exactly 0 sidebar-group-empty`)
	s.Done()
}

// E2E-262: An idle first load settles without moving, the web font included
func TestE2E262(t *testing.T) {
	s := scenarios.New(t, "E2E-262")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows content-breadcrumb`)
	s.And(`the page shows file-view`)
	s.And(`no non-input layout shift occurred in the first 3 seconds`)
	s.Done()
}

// E2E-263: Hovering a breadcrumb link moves no part of the trail, because hover feedback is colour and not weight
func TestE2E263(t *testing.T) {
	s := scenarios.New(t, "E2E-263")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers the breadcrumb link "Workspace overview"`)
	s.Then(`the hovered link's width changed by no more than 2 pixels`)
	s.And(`the following breadcrumb-sep moved by no more than 2 pixels`)
	s.And(`content-breadcrumb's current crumb moved by no more than 2 pixels`)
	s.Done()
}

// E2E-264: A breadcrumb link's hover resolves the hover colour token, which is the feedback channel the design chose
func TestE2E264(t *testing.T) {
	s := scenarios.New(t, "E2E-264")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers the breadcrumb link "Workspace overview"`)
	s.Then(`the hovered link resolves "color" from the token "--link-color-hover"`)
	s.Done()
}

// E2E-265: The crumb that is not a link answers a hover with nothing at all, because there is nothing there to press
func TestE2E265(t *testing.T) {
	s := scenarios.New(t, "E2E-265")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers content-breadcrumb's current crumb`)
	s.Then(`content-breadcrumb's current crumb resolves "color" from the token "--text-primary"`)
	s.And(`hovering it changes neither its colour nor its geometry`)
	s.Done()
}

// E2E-266: Inventory data arriving moves no status chip, in either direction
func TestE2E266(t *testing.T) {
	s := scenarios.New(t, "E2E-266")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`at least one chip is pending when the list first renders`)
	s.And(`every inventory chip has settled onto a live status`)
	s.And(`no chip's box moved or resized by more than 2 pixels`)
	s.Done()
}

// E2E-267: Every chip does reach its live status and states one the vocabulary knows, so stability is never bought by showing nothing
func TestE2E267(t *testing.T) {
	s := scenarios.New(t, "E2E-267")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-inventory`)
	s.And(`every inventory chip has settled onto a live status`)
	s.And(`every inventory chip carries a known status`)
	s.Done()
}

// E2E-268: Every section's file page carries the same header block, the architecture page included
func TestE2E268(t *testing.T) {
	s := scenarios.New(t, "E2E-268")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows file-view-kicker`)
	s.And(`the page shows file-view-title`)
	s.And(`the page shows file-view-meta`)
	s.And(`file-view-title has text "architecture.yaml"`)
	s.And(`file-view-title has computed "font-size" = "32px"`)
	s.And(`file-view-kicker matches (?i)Architecture`)
	s.And(`file-view-title sits above file-view-header`)
	s.Done()
}

// E2E-269: Every page's primary title is the one page-title size, so no route shouts at the reader in the display face
func TestE2E269(t *testing.T) {
	s := scenarios.New(t, "E2E-269")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.Then(`every section page's primary title has computed "font-size" = "32px"`)
	s.Done()
}

// E2E-270: The scenarios and builds landings carry a kicker above their heading, as every file page does
func TestE2E270(t *testing.T) {
	s := scenarios.New(t, "E2E-270")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.Then(`the workspace "scenarios" shows a kicker above its heading`)
	s.And(`the workspace "builds" shows a kicker above its heading`)
	s.And(`the workspace "builds" holds a non-empty description paragraph`)
	s.Done()
}

// E2E-271: The save-state is a badge in the file card's own header bar, small, uppercase and led by a dot — not a line of text below the card
func TestE2E271(t *testing.T) {
	s := scenarios.New(t, "E2E-271")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`save-state has attribute "data-save-state" = "idle"`)
	s.And(`save-state's centre lies within file-view-header`)
	s.And(`save-state sits above file-view-editor`)
	s.And(`save-state has computed "font-size" = "11px"`)
	s.And(`save-state has computed "text-transform" = "uppercase"`)
	s.And(`save-state generates a leading pseudo-element`)
	s.Done()
}

// E2E-272: Every control on the overview answers a hover, the refresh action included
func TestE2E272(t *testing.T) {
	s := scenarios.New(t, "E2E-272")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.Then(`hovering overview-action-build-tests changes its colour or background`)
	s.And(`hovering overview-action-build-code changes its colour or background`)
	s.And(`hovering overview-action-refresh changes its colour or background`)
	s.Done()
}

// E2E-273: Every sidebar row answers a hover, whether it was built as a link or not
func TestE2E273(t *testing.T) {
	s := scenarios.New(t, "E2E-273")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`hovering sidebar-group-name changes its colour or background`)
	s.And(`hovering feature-row changes its colour or background`)
	s.And(`hovering scenario-row changes its colour or background`)
	s.And(`hovering new-story-open changes its colour or background`)
	s.Done()
}

// E2E-274: A sidebar row fills on hover whether it is a link or not, so the two kinds of row do not answer differently
func TestE2E274(t *testing.T) {
	s := scenarios.New(t, "E2E-274")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.Then(`hovering scenario-row changes its background`)
	s.And(`hovering feature-row changes its background`)
	s.Done()
}

// E2E-275: The new-story form offers a styled submit, a way out, and a placeholder saying what to type
func TestE2E275(t *testing.T) {
	s := scenarios.New(t, "E2E-275")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks new-story-open`)
	s.Then(`the page shows new-story-form`)
	s.And(`new-story-submit is filled or bordered`)
	s.And(`the page shows new-story-cancel`)
	s.And(`new-story-title has a non-empty placeholder`)
	s.Done()
}

// E2E-276: The chat offers a filled send button and a placeholder inviting a request
func TestE2E276(t *testing.T) {
	s := scenarios.New(t, "E2E-276")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page shows chat-dock-history`)
	s.And(`the page shows chat-dock-new`)
	s.And(`chat-dock-send is filled`)
	s.And(`chat-dock-input has a non-empty placeholder`)
	s.Done()
}

// E2E-277: The scenarios page's kicker names the section scenarios actually live under
func TestE2E277(t *testing.T) {
	s := scenarios.New(t, "E2E-277")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "scenarios"`)
	s.Then(`the page shows file-view-kicker`)
	s.And(`file-view-kicker matches (?i)02\s*[—-]\s*Product\s*/\s*Scenarios`)
	s.But(`file-view-kicker does not match (?i)03|Requirements`)
	s.Done()
}
