//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddweb_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-web/scenarios"
)

// E2E-047: The relay's landing page names the product and says what the list below it holds
func TestE2E047(t *testing.T) {
	s := scenarios.New(t, "E2E-047")
	s.Given(`the relay is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page title is "TrueBDD"`)
	s.And(`the page shows "Workspaces connected to this relay"`)
	s.Done()
}
