//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddweb_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-web/scenarios"
)

// E2E-048: A remote started through a symlinked working directory registers under the canonical real path, never the link
func TestE2E048(t *testing.T) {
	s := scenarios.New(t, "E2E-048")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running through a symlink to its project tree`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the session is listed`)
	s.And(`the session's folder is the project tree's real path`)
	s.And(`the session's row shows the project tree's real path`)
	s.But(`the session's row does not show the symlink path`)
	s.Done()
}

// E2E-049: A remote that stops answering leaves the registry, and its session- and run-scoped endpoints then report the session gone
func TestE2E049(t *testing.T) {
	s := scenarios.New(t, "E2E-049")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "version" on the session as run "R1"`)
	s.When(`the remote is stopped with "SIGSTOP"`)
	s.Then(`the session is not listed`)
	s.And(`a GET to "/api/sessions/{S}" returns status 404`)
	s.And(`the response names error "session_gone"`)
	s.And(`a GET to "/api/sessions/{S}?view=status" returns status 404`)
	s.And(`a GET to "/api/sessions/{S}/runs/{R1}" returns status 404`)
	s.Done()
}

// E2E-050: An epic renders as a section whose story rows carry their lifecycle, their identity and the controls each state allows
func TestE2E050(t *testing.T) {
	s := scenarios.New(t, "E2E-050")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=config] has attribute "status" = "present"`)
	s.And(`inventory-doc[key=registry] has attribute "status" = "present"`)
	s.And(`the page shows epic-section[epic-file=epic-60-inventory-spread.yaml]`)
	s.And(`epic-section[epic-file=epic-60-inventory-spread.yaml] has attribute "epic-number" = "60"`)
	s.And(`epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-title has the "name" of "docs/product/epics/epic-60-inventory-spread.yaml"`)
	s.And(`epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-row has attribute "status" = "parseable"`)
	s.And(`story-row[create-id=60.1] > story-created has attribute "status" = "missing"`)
	s.And(`story-row[create-id=60.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=60.1] > story-applied has attribute "reason" = "missing"`)
	s.And(`story-row[create-id=60.1] > story-refined has text "not recorded"`)
	s.And(`story-row[create-id=60.2] > story-created has attribute "status" = "one"`)
	s.And(`story-row[create-id=60.2] > story-applied has text "1/2"`)
	s.And(`story-row[create-id=60.3] > story-applied has text "2/2"`)
	s.And(`story-row[create-id=60.2] > story-title has the "title" of story "60.2" of "docs/product/epics/epic-60-inventory-spread.yaml"`)
	s.And(`story-row[create-id=60.2] has attribute "declared-id" = "60.2"`)
	s.And(`story-row[create-id=60.2] has attribute "file-id" = "60.2"`)
	s.And(`story-row[create-id=60.2] has attribute "position" = "2"`)
	s.And(`story-row[create-id=60.2] has attribute "epic-number" = "60"`)
	s.And(`story-row[create-id=60.1] > action-create is enabled`)
	s.And(`story-row[create-id=60.1] > fix-toggle is enabled`)
	s.And(`story-row[create-id=60.2] > action-refine is enabled`)
	s.And(`story-row[create-id=60.2] > action-apply is enabled`)
	s.Done()
}

// E2E-051: An epic section's toggle hides its story rows, and says so to assistive technology
func TestE2E051(t *testing.T) {
	s := scenarios.New(t, "E2E-051")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-toggle`)
	s.Then(`epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-toggle has attribute "aria-expanded" = "false"`)
	s.And(`the page does not show story-row[create-id=60.2]`)
	s.Done()
}

// E2E-052: An epic section's toggle brings its story rows back
func TestE2E052(t *testing.T) {
	s := scenarios.New(t, "E2E-052")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-toggle`)
	s.And(`the Product Owner clicks epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-toggle`)
	s.Then(`epic-section[epic-file=epic-60-inventory-spread.yaml] > epic-toggle has attribute "aria-expanded" = "true"`)
	s.And(`the page shows story-row[create-id=60.2]`)
	s.Done()
}

// E2E-053: Refresh reads the project live, so a registry entry written outside the browser reaches the page without a reload
func TestE2E053(t *testing.T) {
	s := scenarios.New(t, "E2E-053")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner appends a scenario covering "60.2-002" to "docs/scenarios.yaml"`)
	s.And(`the Product Owner clicks refresh`)
	s.Then(`story-row[create-id=60.2] > story-applied has text "2/2"`)
	s.Done()
}

// E2E-054: An unparseable engine configuration renders its inventory chip as invalid
func TestE2E054(t *testing.T) {
	s := scenarios.New(t, "E2E-054")
	s.Given(`the "inventory-config-invalid" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=config] has attribute "status" = "invalid"`)
	s.Done()
}

// E2E-055: A file where the stories directory should be renders as not a directory
func TestE2E055(t *testing.T) {
	s := scenarios.New(t, "E2E-055")
	s.Given(`the "inventory-stories-not-a-dir" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=stories-dir] has attribute "status" = "not_a_dir"`)
	s.Done()
}

// E2E-056: A removed checklist renders missing while its siblings stay present
func TestE2E056(t *testing.T) {
	s := scenarios.New(t, "E2E-056")
	s.Given(`the "inventory-checklist-missing" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=checklist-us-apply] has attribute "status" = "missing"`)
	s.And(`inventory-doc[key=checklist-us-create] has attribute "status" = "present"`)
	s.Done()
}

// E2E-057: An unparseable checklist renders invalid while its siblings stay present
func TestE2E057(t *testing.T) {
	s := scenarios.New(t, "E2E-057")
	s.Given(`the "inventory-checklist-invalid" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=checklist-us-refine] has attribute "status" = "invalid"`)
	s.And(`inventory-doc[key=checklist-us-create] has attribute "status" = "present"`)
	s.Done()
}

// E2E-058: A registry holding an empty map renders present but empty, distinct from missing
func TestE2E058(t *testing.T) {
	s := scenarios.New(t, "E2E-058")
	s.Given(`the "inventory-registry-present-empty" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`inventory-doc[key=registry] has attribute "status" = "present_empty"`)
	s.Done()
}

// E2E-059: An architectural spec at a non-default path warns about the relocation while still scanning the configured location
func TestE2E059(t *testing.T) {
	s := scenarios.New(t, "E2E-059")
	s.Given(`the "inventory-architecture-path-mismatch" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows path-mismatch-warning`)
	s.And(`inventory-doc[key=architecture] has attribute "status" = "present"`)
	s.Done()
}

// E2E-060: An unparseable epic renders a section with an invalid row and no toggle, because a control that controls nothing is a lie
func TestE2E060(t *testing.T) {
	s := scenarios.New(t, "E2E-060")
	s.Given(`the "inventory-epic-malformed" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows epic-section[epic-file=epic-70-broken.yaml]`)
	s.And(`epic-section[epic-file=epic-70-broken.yaml] > epic-row has attribute "status" = "invalid"`)
	s.But(`the page shows exactly 0 epic-section[epic-file=epic-70-broken.yaml] > epic-toggle`)
	s.Done()
}

// E2E-061: Two epics whose filenames claim one number are both flagged, and the story id they collide on still resolves inside each section
func TestE2E061(t *testing.T) {
	s := scenarios.New(t, "E2E-061")
	s.Given(`the "inventory-epic-duplicate-numbers" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows epic-section[epic-file=epic-07-alpha.yaml] > epic-flag-duplicate-number`)
	s.And(`the page shows epic-section[epic-file=epic-07-beta.yaml] > epic-flag-duplicate-number`)
	s.And(`the page shows epic-section[epic-file=epic-07-alpha.yaml] > story-row[create-id=7.1]`)
	s.And(`the page shows epic-section[epic-file=epic-07-beta.yaml] > story-row[create-id=7.1]`)
	s.Done()
}

// E2E-062: An epic whose filename and document id disagree is flagged, and its story row exposes all three identities it holds at once
func TestE2E062(t *testing.T) {
	s := scenarios.New(t, "E2E-062")
	s.Given(`the "inventory-epic-id-mismatch" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows epic-section[epic-file=epic-42-identity-mismatch.yaml] > epic-flag-id-mismatch`)
	s.And(`the page shows story-row[create-id=42.1]`)
	s.And(`story-row[create-id=42.1] has attribute "declared-id" = "77.5"`)
	s.And(`story-row[create-id=42.1] has attribute "file-id" = "88.9"`)
	s.And(`story-row[create-id=42.1] > story-created has attribute "status" = "one"`)
	s.Done()
}

// E2E-063: Two stories declaring one id flag both of the position-derived rows they produced
func TestE2E063(t *testing.T) {
	s := scenarios.New(t, "E2E-063")
	s.Given(`the "inventory-story-duplicate-ids" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows story-row[create-id=70.1] > story-flag-duplicate-declared-id`)
	s.And(`the page shows story-row[create-id=70.2] > story-flag-duplicate-declared-id`)
	s.Done()
}

// E2E-064: Two files matching one story's glob render it ambiguous rather than silently picking one
func TestE2E064(t *testing.T) {
	s := scenarios.New(t, "E2E-064")
	s.Given(`the "inventory-story-ambiguous-files" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`story-row[create-id=70.1] > story-created has attribute "status" = "ambiguous"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "reason" = "ambiguous"`)
	s.Done()
}

// E2E-065: An unparseable story renders created invalid and its applied count unknown for that reason
func TestE2E065(t *testing.T) {
	s := scenarios.New(t, "E2E-065")
	s.Given(`the "inventory-story-malformed" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`story-row[create-id=70.1] > story-created has attribute "status" = "invalid"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "reason" = "invalid"`)
	s.Done()
}

// E2E-066: A story in the retired format is readable but ineligible to apply, and says which of the two it is
func TestE2E066(t *testing.T) {
	s := scenarios.New(t, "E2E-066")
	s.Given(`the "inventory-story-deprecated-format" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`story-row[create-id=70.1] > story-created has attribute "status" = "one"`)
	s.And(`the page shows story-row[create-id=70.1] > story-flag-deprecated-format`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "reason" = "deprecated_format"`)
	s.Done()
}

// E2E-067: A story with no acceptance criteria is ineligible to apply, because there is nothing to merge
func TestE2E067(t *testing.T) {
	s := scenarios.New(t, "E2E-067")
	s.Given(`the "inventory-story-no-acs" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`story-row[create-id=70.1] > story-created has attribute "status" = "one"`)
	s.And(`the page shows story-row[create-id=70.1] > story-flag-no-acs`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "reason" = "no_acceptance_criteria"`)
	s.Done()
}

// E2E-068: A story whose internal id is blank is flagged for it rather than treated as having none
func TestE2E068(t *testing.T) {
	s := scenarios.New(t, "E2E-068")
	s.Given(`the "inventory-story-empty-internal-id" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`story-row[create-id=70.1] > story-created has attribute "status" = "one"`)
	s.And(`the page shows story-row[create-id=70.1] > story-flag-empty-internal-id`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "status" = "unknown"`)
	s.And(`story-row[create-id=70.1] > story-applied has attribute "reason" = "empty_internal_id"`)
	s.Done()
}

// E2E-069: An epic whose filename is not canonical renders its header and flag with no toggle and no story rows, because nothing under it is addressable
func TestE2E069(t *testing.T) {
	s := scenarios.New(t, "E2E-069")
	s.Given(`the "inventory-epic-noncanonical-filename" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows epic-section[epic-file=epic-7-noncanon.yaml] > epic-flag-noncanonical-filename`)
	s.But(`the page shows exactly 0 epic-section[epic-file=epic-7-noncanon.yaml] > epic-toggle`)
	s.And(`the page shows exactly 0 story-row[create-id=7.1]`)
	s.Done()
}

// E2E-070: A command outside the typed allowlist is refused before anything runs, so a shell fragment can never reach a subprocess
func TestE2E070(t *testing.T) {
	s := scenarios.New(t, "E2E-070")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a POST to "/api/sessions/{S}/runs" with the dispatch body for command "version; echo pwned" returns status 400`)
	s.Done()
}

// E2E-071: While one owner holds a non-terminal run, the same token returns that run and a fresh token is refused, so an owner can never hold two
func TestE2E071(t *testing.T) {
	s := scenarios.New(t, "E2E-071")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner dispatches "prompt-probe" on the session as run "R1"`)
	s.Then(`run "R1" publishes a "choice" prompt`)
	s.And(`dispatching the same token returns run "R1" with status 200`)
	s.And(`a POST to "/api/sessions/{S}/runs" with the dispatch body for command "version" returns status 409`)
	s.Done()
}

// E2E-072: An owner with an active run has its own build controls disabled
func TestE2E072(t *testing.T) {
	s := scenarios.New(t, "E2E-072")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner opens the session page of "A"`)
	s.Then(`action-build-tests is disabled`)
	s.And(`action-build-code is disabled`)
	s.Done()
}

// E2E-073: A sibling session on the same folder is warned about the activity but left able to act, because the folder lock decides and not the relay
func TestE2E073(t *testing.T) {
	s := scenarios.New(t, "E2E-073")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner opens the session page of "B"`)
	s.Then(`the page shows folder-warning-banner`)
	s.And(`action-build-tests is enabled`)
	s.And(`action-build-code is enabled`)
	s.Done()
}

// E2E-074: A frozen CLI's dispatch times out rather than becoming a run the relay holds, because the relay keeps no run state at all
func TestE2E074(t *testing.T) {
	s := scenarios.New(t, "E2E-074")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the remote is stopped with "SIGSTOP"`)
	s.Then(`a POST to "/api/sessions/{S}/runs" with the dispatch body for command "version" returns status 504 or 404`)
	s.Done()
}

// E2E-075: A browser mutation is admitted only with both the exact allowed origin and the expected host
func TestE2E075(t *testing.T) {
	s := scenarios.New(t, "E2E-075")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a POST to "/api/sessions/{S}/runs" with the dispatch body and headers "origin: http://evil.example" returns status 403`)
	s.And(`a POST to "/api/sessions/{S}/runs" with the dispatch body and headers "origin: null" returns status 403`)
	s.And(`a POST to "/api/sessions/{S}/runs" with the dispatch body returns status 403`)
	s.And(`a POST to "/api/sessions/{S}/runs" with the dispatch body and headers "host: harness.example.com; origin: {BASE}" returns status 403`)
	s.And(`a POST to "/api/sessions/{S}/runs" with the dispatch body and headers "origin: {BASE}" does not return status 403`)
	s.Done()
}

// E2E-076: Every agent route refuses a present foreign origin and accepts an absent one on a loopback host, because the Go client sends no origin at all
func TestE2E076(t *testing.T) {
	s := scenarios.New(t, "E2E-076")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a POST to "/api/agent/register" with the register body and headers "origin: http://evil.example" returns status 403`)
	s.And(`a POST to "/api/agent/register" with the register body and headers "host: harness.example.com" returns status 403`)
	s.And(`a POST to "/api/agent/register" with the register body returns status 200`)
	s.And(`a POST to "/api/agent/poll" with the poll body and headers "origin: http://evil.example" returns status 403`)
	s.And(`a POST to "/api/agent/poll" with the poll body and headers "host: harness.example.com" returns status 403`)
	s.And(`a POST to "/api/agent/poll" with the poll body returns status 204 or 200`)
	s.And(`a POST to "/api/agent/reply" with the reply body and headers "origin: http://evil.example" returns status 403`)
	s.And(`a POST to "/api/agent/reply" with the reply body does not return status 403`)
	s.And(`a GET to "/api/sessions" with headers "host: harness.example.com" returns status 403`)
	s.And(`a GET to "/api/sessions" returns status 200`)
	s.Done()
}

// E2E-077: An opaque origin and a text content type are refused on every agent route before any state is touched
func TestE2E077(t *testing.T) {
	s := scenarios.New(t, "E2E-077")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a POST to each agent route with headers "origin: null" returns status 403`)
	s.And(`a POST to each agent route with headers "origin: http://evil.example" returns status 403`)
	s.And(`a POST to each agent route with headers "content-type: text/plain" returns status 415`)
	s.And(`a POST to each agent route with headers "content-type: application/json" does not return status 403`)
	s.Done()
}

// E2E-078: A reply larger than the budget it was given is refused with a correlated answer rather than a blind timeout, because the correlation travels outside the body
func TestE2E078(t *testing.T) {
	s := scenarios.New(t, "E2E-078")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`an agent "S1" is registered`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the register response carries a numeric reply budget`)
	s.And(`a POST to "/api/agent/reply" with a body one byte over the reply budget returns status 413`)
	s.Done()
}

// E2E-079: Deployed mode is set by configuration and never inferred from the host, so a loopback relay cannot be talked into it by a spoofed header
func TestE2E079(t *testing.T) {
	s := scenarios.New(t, "E2E-079")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running with "HARNESS_DEPLOYED" set to "1"`)
	s.And(`a second relay is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a GET to "/api/sessions" with headers "host: true-bdd-app.vercel.app" returns status 200`)
	s.And(`a GET to "/api/sessions/{MISSING}" with headers "host: true-bdd-app.vercel.app" returns status 404`)
	s.And(`the response names error "session_gone"`)
	s.And(`a GET to "/api/sessions/{MISSING}/runs/{MISSING}" with headers "host: true-bdd-app.vercel.app" returns status 404`)
	s.And(`a POST to "/api/agent/register" with the register body and headers "host: true-bdd-app.vercel.app" returns status 200`)
	s.And(`a POST to "/api/agent/poll" with the poll body and headers "host: true-bdd-app.vercel.app" returns status 204`)
	s.And(`a POST to "/api/agent/reply" with the reply body and headers "host: true-bdd-app.vercel.app" returns status 409`)
	s.And(`a GET to "/api/sessions" on the second relay with headers "host: true-bdd-app.vercel.app" returns status 403`)
	s.Done()
}

// E2E-080: In deployed mode a mutation's origin is matched against the forwarded public host and never the raw one, and a forwarded header that is ambiguous or not http establishes no host at all
func TestE2E080(t *testing.T) {
	s := scenarios.New(t, "E2E-080")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running with "HARNESS_DEPLOYED" set to "1"`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "host: true-bdd-app.vercel.app; origin: https://true-bdd-app.vercel.app" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "x-forwarded-host: true-bdd-app.vercel.app; x-forwarded-proto: https; origin: https://true-bdd-app.vercel.app" returns status 404`)
	s.And(`the response names error "session_gone"`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "x-forwarded-host: true-bdd-app.vercel.app, evil.example; x-forwarded-proto: https; origin: https://true-bdd-app.vercel.app" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "x-forwarded-host: true-bdd-app.vercel.app; x-forwarded-proto: file; origin: https://true-bdd-app.vercel.app" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "host: true-bdd-app.vercel.app; origin: http://evil.example" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "host: true-bdd-app.vercel.app; origin: null" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs" with the dispatch body and headers "host: true-bdd-app.vercel.app" returns status 403`)
	s.And(`a POST to "/api/sessions/{MISSING}/runs/{MISSING}/answer" with the answer body and headers "host: true-bdd-app.vercel.app; origin: http://evil.example" returns status 403`)
	s.Done()
}

// E2E-081: A relay restart leaves the session listed unchanged, because the registry outlives the process that serves it
func TestE2E081(t *testing.T) {
	s := scenarios.New(t, "E2E-081")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "version" on the session as run "R1"`)
	s.And(`run "R1" reaches a terminal state`)
	s.When(`the relay restarts`)
	s.And(`the Product Owner opens the session page`)
	s.Then(`the session is listed`)
	s.And(`the session's id, pid and connect time are unchanged`)
	s.And(`run "R1" has outcome "ok"`)
	s.And(`the page shows run-row[run-id=R1]`)
	s.Done()
}

// E2E-082: An agent's credentials and its queued work both survive a relay restart, so a dispatch in flight when the process died is still delivered exactly once
func TestE2E082(t *testing.T) {
	s := scenarios.New(t, "E2E-082")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`an agent "S1" is registered and never polls`)
	s.And(`the Product Owner dispatches "version" on session "S1" as request "Q1"`)
	s.And(`the work queue for session "S1" is non-empty`)
	s.When(`the relay restarts`)
	s.And(`agent "S1" polls as work "W1"`)
	s.Then(`agent "S1" was not rejected for its original credentials`)
	s.And(`work "W1" has type "dispatch"`)
	s.And(`work "W1" carries the dispatch payload of request "Q1"`)
	s.And(`work "W1" is not redelivered`)
	s.Done()
}

// E2E-083: A story title opens a modal that names the story accessibly and keeps keyboard focus inside it
func TestE2E083(t *testing.T) {
	s := scenarios.New(t, "E2E-083")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=60.2] > story-title`)
	s.And(`the Product Owner presses "Tab" 8 times`)
	s.Then(`story-modal has attribute "story-id" = "60.2"`)
	s.And(`story-modal-title contains text "60.2"`)
	s.And(`story-modal-title has the "title" of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`focus is inside story-modal`)
	s.And(`refresh is not focused`)
	s.Done()
}

// E2E-084: The modal's review panel renders the story's statement, acceptance criteria and every step kind from the file itself
func TestE2E084(t *testing.T) {
	s := scenarios.New(t, "E2E-084")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=60.2] > story-title`)
	s.Then(`story-modal-statement holds the statement of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-ac[ac-id=AC-1] holds acceptance criterion 1 of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-ac[ac-id=AC-2] holds acceptance criterion 2 of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-step[kind=given] holds the first "given" step of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-step[kind=when] holds the first "when" step of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-step[kind=then] holds the first "then" step of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-step[kind=and] holds the first "and" step of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-step[kind=but] holds the first "but" step of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.And(`story-modal-applied contains text "1/2"`)
	s.And(`story-modal-refined contains text "not recorded"`)
	s.And(`the page shows story-modal-status`)
	s.Done()
}

// E2E-085: The modal's tablist answers the arrow keys, and its raw panel is the file's bytes rather than a rendering of them
func TestE2E085(t *testing.T) {
	s := scenarios.New(t, "E2E-085")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner focuses story-modal-tab-review`)
	s.And(`the Product Owner presses "ArrowRight"`)
	s.Then(`story-modal-tab-raw has attribute "aria-selected" = "true"`)
	s.And(`story-modal-tab-review has attribute "aria-selected" = "false"`)
	s.And(`story-modal-raw holds the bytes of "docs/product/stories/60.2-summary-shared-docs.yaml"`)
	s.Done()
}

// E2E-086: A click on the modal's own panel does not close it, because a panel is not a backdrop
func TestE2E086(t *testing.T) {
	s := scenarios.New(t, "E2E-086")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner clicks story-modal-panel`)
	s.Then(`the page shows story-modal`)
	s.Done()
}

// E2E-087: Escape closes the modal and gives focus back to the title that opened it
func TestE2E087(t *testing.T) {
	s := scenarios.New(t, "E2E-087")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner presses "Escape"`)
	s.Then(`the page does not show story-modal`)
	s.And(`story-row[create-id=60.2] > story-title is focused`)
	s.Done()
}

// E2E-088: The close button closes the modal and gives focus back to the title that opened it
func TestE2E088(t *testing.T) {
	s := scenarios.New(t, "E2E-088")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner clicks story-modal-close`)
	s.Then(`the page does not show story-modal`)
	s.And(`story-row[create-id=60.2] > story-title is focused`)
	s.Done()
}

// E2E-089: A click on the backdrop closes the modal and gives focus back to the title that opened it
func TestE2E089(t *testing.T) {
	s := scenarios.New(t, "E2E-089")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner clicks the modal backdrop`)
	s.Then(`the page does not show story-modal`)
	s.And(`story-row[create-id=60.2] > story-title is focused`)
	s.Done()
}

// E2E-090: An arrow key moves focus to the destination tab, not only its selected state, so the keyboard lands where the eye does
func TestE2E090(t *testing.T) {
	s := scenarios.New(t, "E2E-090")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner focuses story-modal-tab-review`)
	s.And(`the Product Owner presses "ArrowRight"`)
	s.Then(`story-modal-tab-raw is focused`)
	s.And(`story-modal-tab-raw has attribute "aria-selected" = "true"`)
	s.Done()
}

// E2E-091: The opposite arrow key rolls focus and selection back to the tab it came from
func TestE2E091(t *testing.T) {
	s := scenarios.New(t, "E2E-091")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.2"`)
	s.When(`the Product Owner focuses story-modal-tab-review`)
	s.And(`the Product Owner presses "ArrowRight"`)
	s.And(`the Product Owner presses "ArrowLeft"`)
	s.Then(`story-modal-tab-review is focused`)
	s.And(`story-modal-tab-review has attribute "aria-selected" = "true"`)
	s.Done()
}

// E2E-092: A story the epic declares but no file holds still opens, reviewing the declared content under a notice saying it was never created
func TestE2E092(t *testing.T) {
	s := scenarios.New(t, "E2E-092")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=60.1] > story-title`)
	s.Then(`story-modal-statement holds the statement declared for story "60.1" in "docs/product/epics/epic-60-inventory-spread.yaml"`)
	s.And(`story-modal-ac[ac-id=AC-1] holds acceptance criterion 1 declared for story "60.1" in "docs/product/epics/epic-60-inventory-spread.yaml"`)
	s.And(`story-modal-notice has attribute "reason" = "not_created"`)
	s.But(`the page shows exactly 0 story-modal-tab-raw`)
	s.Done()
}

// E2E-093: A story whose glob matches two files opens on the declared content under a notice that counts the matches
func TestE2E093(t *testing.T) {
	s := scenarios.New(t, "E2E-093")
	s.Given(`the "inventory-story-ambiguous-files" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=70.1] > story-title`)
	s.Then(`story-modal-statement holds the statement declared for story "70.1" in "docs/product/epics/epic-70-inventory.yaml"`)
	s.And(`story-modal-notice has attribute "reason" = "ambiguous"`)
	s.And(`story-modal-notice contains text "2"`)
	s.Done()
}

// E2E-094: An unparseable story opens on its raw bytes with an error banner, and its review tab still falls back to what the epic declares
func TestE2E094(t *testing.T) {
	s := scenarios.New(t, "E2E-094")
	s.Given(`the "inventory-story-malformed" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=70.1] > story-title`)
	s.And(`the Product Owner clicks story-modal-tab-review`)
	s.Then(`story-modal-tab-raw was selected when the modal opened`)
	s.And(`the page shows story-modal-error`)
	s.And(`story-modal-raw holds the bytes of "docs/product/stories/70.1-broken.yaml"`)
	s.And(`story-modal-tab-review does not have attribute "aria-disabled" = "true"`)
	s.And(`story-modal-statement holds the statement declared for story "70.1" in "docs/product/epics/epic-70-inventory.yaml"`)
	s.Done()
}

// E2E-095: A story that vanishes from disk while its modal is open keeps the modal open and says it changed, rather than unmounting under the reader
func TestE2E095(t *testing.T) {
	s := scenarios.New(t, "E2E-095")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.And(`the Product Owner has opened the modal for story "60.3"`)
	s.When(`the Product Owner removes the "60.3" story declaration from "docs/product/epics/epic-60-inventory-spread.yaml"`)
	s.Then(`story-modal-notice has attribute "reason" = "changed_on_disk"`)
	s.And(`the page shows story-modal`)
	s.Done()
}

// E2E-096: An inventory that could not fit its budget says so in a banner, and a row it had to omit content for opens on a notice instead of pretending to have it
func TestE2E096(t *testing.T) {
	s := scenarios.New(t, "E2E-096")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running with "MAX_INVENTORY_REQUEST_BYTES" set to "5120"`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has the session page open`)
	s.When(`the Product Owner clicks story-row[create-id=60.2] > story-title`)
	s.Then(`the page shows inventory-truncated-banner`)
	s.And(`the page shows story-modal-notice`)
	s.Done()
}

// E2E-097: A budget below the smallest possible request is reported out of band, so the page stays honest with no snapshot at all
func TestE2E097(t *testing.T) {
	s := scenarios.New(t, "E2E-097")
	s.Given(`the "p3-inventory-spread" project tree`)
	s.And(`the relay is running with "MAX_INVENTORY_REQUEST_BYTES" set to "200"`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens the session page`)
	s.Then(`the page shows inventory-truncated-banner`)
	s.And(`inventory-truncated-banner contains text "limit too small"`)
	s.Done()
}

// E2E-098: A replacement remote reconciles a dead owner's orphan before it registers, ending the stale run as abandoned and freeing the folder
func TestE2E098(t *testing.T) {
	s := scenarios.New(t, "E2E-098")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`remote "A" is stopped with "SIGKILL"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner dispatches "version" on session "B" as run "R2"`)
	s.Then(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "abandoned"`)
	s.And(`run "R2" reaches a terminal state`)
	s.And(`run "R2" has outcome "ok"`)
	s.Done()
}

// E2E-099: A remote booting beside a live sibling leaves the sibling's run alone, because liveness is verified rather than inferred from a pid
func TestE2E099(t *testing.T) {
	s := scenarios.New(t, "E2E-099")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`a remote is running as "B" in the same project tree`)
	s.Then(`run "R1" is not terminal`)
	s.And(`remote "A" is running`)
	s.Done()
}

// E2E-100: A session that never existed reads as gone, while one that is registered but not answering reads as a timeout — registered is not the same as reachable
func TestE2E100(t *testing.T) {
	s := scenarios.New(t, "E2E-100")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`an agent "S1" is registered and never polls`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a GET to "/api/sessions/{MISSING}?view=status" returns status 404`)
	s.And(`a GET to "/api/sessions/{MISSING}/runs/{MISSING}" returns status 404`)
	s.And(`a GET to "/api/sessions/{S1}?view=status" returns status 504`)
	s.Done()
}

// E2E-101: A poll with the wrong capability token or a superseded epoch is rejected, and so is a reply arriving on the epoch a re-register retired
func TestE2E101(t *testing.T) {
	s := scenarios.New(t, "E2E-101")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`an agent "S1" is registered and never polls`)
	s.When(`agent "S1" registers again`)
	s.Then(`the new connection epoch is greater than the old one`)
	s.And(`a poll for "S1" with the wrong capability token is rejected`)
	s.And(`a poll for "S1" on the superseded epoch is rejected`)
	s.And(`a reply for "S1" on the superseded epoch is rejected`)
	s.Done()
}

// E2E-102: Concurrent reads of different kinds each receive their own reply, because the relay routes by correlation and never by arrival order
func TestE2E102(t *testing.T) {
	s := scenarios.New(t, "E2E-102")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "version" on the session as run "R1"`)
	s.And(`run "R1" reaches a terminal state`)
	s.When(`the Product Owner reads the session status, the session detail and run "R1" concurrently 12 times`)
	s.Then(`every session status reply names the session it was asked about`)
	s.And(`every session detail reply names that session and carries an inventory`)
	s.And(`every run reply names run "R1" and that session`)
	s.Done()
}

// E2E-103: A re-submitted dispatch and a re-submitted answer are exact retries, so a lost response never doubles a run or an answer
func TestE2E103(t *testing.T) {
	s := scenarios.New(t, "E2E-103")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "prompt-probe" on the session as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner answers the pending prompt of run "R1" with "1"`)
	s.Then(`dispatching the same token returns run "R1" with status 200`)
	s.And(`answering the same prompt with "1" returns status 200`)
	s.And(`answering the same prompt with "2" returns status 409`)
	s.And(`run "R1" advances past the prompt`)
	s.Done()
}

// E2E-104: A prompt is a native modal that keeps focus, and Escape does not answer it
func TestE2E104(t *testing.T) {
	s := scenarios.New(t, "E2E-104")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "prompt-probe" on the session as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.When(`the Product Owner presses "Escape"`)
	s.Then(`prompt-dialog has attribute "kind" = "choice"`)
	s.And(`focus is inside prompt-dialog`)
	s.And(`the page shows prompt-dialog`)
	s.And(`run "R1" still waits on the same prompt`)
	s.Done()
}

// E2E-105: A prompt answered through the browser advances the run through all three of its kinds
func TestE2E105(t *testing.T) {
	s := scenarios.New(t, "E2E-105")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "prompt-probe" on the session as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.When(`the Product Owner clicks prompt-choice-apply`)
	s.Then(`run "R1" publishes a "clarify" prompt`)
	s.And(`answering the clarify prompt with "1" advances run "R1" to a "freetext" prompt`)
	s.And(`answering the freetext prompt with "final probe feedback" clears prompt-dialog`)
	s.Done()
}

// E2E-106: An answer the relay rejects leaves the prompt open with the reason on it, rather than closing on a failure
func TestE2E106(t *testing.T) {
	s := scenarios.New(t, "E2E-106")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner dispatches "prompt-probe" on the session as run "R1"`)
	s.And(`the Product Owner has the run page for run "R1" open`)
	s.And(`run "R1" publishes a "clarify" prompt`)
	s.When(`the Product Owner fills prompt-answer-input with ""`)
	s.And(`the Product Owner clicks prompt-answer-submit`)
	s.Then(`the page shows prompt-dialog-error`)
	s.And(`the page shows prompt-dialog`)
	s.Done()
}

// E2E-107: A command running against a folder holds it, so a sibling command on the same folder fails fast and says the folder is locked
func TestE2E107(t *testing.T) {
	s := scenarios.New(t, "E2E-107")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "A" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner dispatches "prompt-probe" on session "B" as run "R2"`)
	s.Then(`run "R2" reaches a terminal state`)
	s.And(`run "R2" has outcome "error"`)
	s.And(`run "R2" has error detail "folder_locked"`)
	s.Done()
}

// E2E-108: Another owner's run is readable through any live session on the project but answerable only through the one that owns it
func TestE2E108(t *testing.T) {
	s := scenarios.New(t, "E2E-108")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running`)
	s.And(`a remote is running as "A"`)
	s.And(`a remote is running as "B" in the same project tree`)
	s.And(`the Product Owner dispatches "prompt-probe" on session "B" as run "R1"`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.When(`the Product Owner answers the pending prompt of run "R1" through session "A" with "1"`)
	s.Then(`run "R1" is not answerable through session "A"`)
	s.And(`run "R1" is answerable through session "B"`)
	s.And(`the answer returned status 409`)
	s.And(`run "R1" still waits on the same prompt`)
	s.And(`answering the pending prompt of run "R1" through session "B" with "1" advances it past the prompt`)
	s.Done()
}

// E2E-109: A session registered on one relay instance is visible on the other, in both directions, because the registry is shared rather than held in a process
func TestE2E109(t *testing.T) {
	s := scenarios.New(t, "E2E-109")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.When(`an agent "S1" is registered on relay "B"`)
	s.And(`an agent "S2" is registered on relay "A"`)
	s.Then(`session "S1" is listed on relay "A"`)
	s.And(`session "S2" is listed on relay "B"`)
	s.Done()
}

// E2E-110: A dispatch enqueued on one instance is claimed and answered on the other, delivered exactly once and never re-served from a retained body
func TestE2E110(t *testing.T) {
	s := scenarios.New(t, "E2E-110")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`an agent "S1" is registered on relay "B"`)
	s.And(`the Product Owner dispatches "version" on session "S1" through relay "A" as request "Q1"`)
	s.When(`agent "S1" polls relay "B" as work "W1"`)
	s.And(`agent "S1" replies to work "W1"`)
	s.Then(`work "W1" has type "dispatch"`)
	s.And(`work "W1" carries the dispatch payload of request "Q1"`)
	s.And(`request "Q1" completes with status 201`)
	s.And(`the Redis key "reply:W1" is gone`)
	s.And(`work "W1" is not redelivered`)
	s.Done()
}

// E2E-111: A read issued on one instance is served by the CLI polling the other
func TestE2E111(t *testing.T) {
	s := scenarios.New(t, "E2E-111")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`an agent "S1" is registered on relay "B"`)
	s.And(`the Product Owner reads the session detail of "S1" on relay "A" as request "Q1"`)
	s.When(`agent "S1" polls relay "B" as work "W1"`)
	s.And(`agent "S1" replies to work "W1"`)
	s.Then(`work "W1" has type "query"`)
	s.And(`request "Q1" completes with status 200`)
	s.Done()
}

// E2E-112: The queue a session may hold is counted across both instances, so capacity cannot be doubled by asking the other one
func TestE2E112(t *testing.T) {
	s := scenarios.New(t, "E2E-112")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis with "HARNESS_MAX_PER_SESSION_QUEUE" set to "2"`)
	s.And(`an agent "S1" is registered on relay "B"`)
	s.When(`two claimed reads fill the queue for session "S1"`)
	s.Then(`a further status read of "S1" on relay "A" returns status 503`)
	s.And(`a further status read of "S1" on relay "B" returns status 503`)
	s.Done()
}

// E2E-113: A reply carrying the wrong token for a session registered on the other instance is refused as a bad token, proving the shared registry authenticated it
func TestE2E113(t *testing.T) {
	s := scenarios.New(t, "E2E-113")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`an agent "S1" is registered on relay "A"`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`a reply for "S1" on relay "B" with the wrong capability token returns status 409`)
	s.And(`the response names error "bad_token"`)
	s.Done()
}

// E2E-114: A fix run drives choice, clarify and freetext to a clean completion across two instances, each answer consumed exactly once
func TestE2E114(t *testing.T) {
	s := scenarios.New(t, "E2E-114")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`a remote is running against relay "B"`)
	s.When(`the Product Owner dispatches "prompt-probe" on the session with fix through relay "A" as run "R1"`)
	s.Then(`run "R1" has fix set`)
	s.And(`run "R1" publishes a "choice" prompt`)
	s.And(`answering the same prompt with "1" returns status 200`)
	s.And(`run "R1" publishes a "clarify" prompt`)
	s.And(`run "R1" publishes a "freetext" prompt`)
	s.And(`run "R1" reaches a terminal state`)
	s.And(`run "R1" has outcome "ok"`)
	s.Done()
}

// E2E-115: A run's output is readable while it is still running, so a long run is watchable rather than a wait for a final blob
func TestE2E115(t *testing.T) {
	s := scenarios.New(t, "E2E-115")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`a remote is running against relay "B"`)
	s.When(`the Product Owner dispatches "prompt-probe" on the session through relay "A" as run "R1"`)
	s.Then(`run "R1" streams output before it is answered`)
	s.And(`run "R1" is not terminal`)
	s.And(`run "R1" streams more output after it is answered`)
	s.Done()
}

// E2E-116: A claimed dispatch that outran the browser's deadline accepts one late reply and refuses the second, because the relay forwards rather than stores
func TestE2E116(t *testing.T) {
	s := scenarios.New(t, "E2E-116")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`an agent "S1" is registered on relay "A"`)
	s.And(`the Product Owner dispatches "version" on session "S1" through relay "A" as request "Q1"`)
	s.When(`agent "S1" polls relay "B" as work "W1"`)
	s.Then(`request "Q1" completes with status 504`)
	s.And(`replying to work "W1" on relay "B" returns status 200`)
	s.And(`replying to work "W1" on relay "B" again returns status 409`)
	s.And(`the Redis key "reply:W1" does not hold the late reply`)
	s.Done()
}

// E2E-117: A run the CLI committed while the browser gave up is recovered by re-dispatching its token, and the project still holds exactly one run
func TestE2E117(t *testing.T) {
	s := scenarios.New(t, "E2E-117")
	s.Given(`the "bare-host" project tree`)
	s.And(`relays "A" and "B" share one Redis`)
	s.And(`a remote is running against relay "B"`)
	s.And(`the Product Owner dispatches "version" on the session through relay "A" as run "R1"`)
	s.And(`run "R1" reaches a terminal state`)
	s.When(`the Product Owner dispatches "version" on the session reusing the token of run "R1"`)
	s.Then(`dispatching the same token returns run "R1" with status 200`)
	s.And(`the project has exactly 1 run`)
	s.And(`the project's only run is run "R1"`)
	s.Done()
}

// E2E-118: Sweeping a session that stopped answering reclaims the capacity its abandoned work held, so dead sessions cannot exhaust the relay over time
func TestE2E118(t *testing.T) {
	s := scenarios.New(t, "E2E-118")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running with "HARNESS_MAX_GLOBAL_QUEUE" set to "1"`)
	s.And(`an agent "S1" is registered and never polls`)
	s.And(`the Product Owner reads the session detail of "S1" as request "Q1"`)
	s.When(`session "S1" is swept out of the registry`)
	s.Then(`a further session detail read of "S1" returned status 503 before the sweep`)
	s.And(`request "Q1" completes with status 404`)
	s.And(`a read for a freshly registered session is enqueued and served`)
	s.Done()
}

// E2E-119: A late reply arriving after the orphan window is refused as unknown work, because the record it would correlate to was reclaimed
func TestE2E119(t *testing.T) {
	s := scenarios.New(t, "E2E-119")
	s.Given(`the "bare-host" project tree`)
	s.And(`the relay is running with "HARNESS_ORPHAN_TTL_SEC" set to "5"`)
	s.And(`an agent "S1" is registered and never polls`)
	s.And(`the Product Owner dispatches "version" on session "S1" as request "Q1"`)
	s.When(`agent "S1" polls as work "W1"`)
	s.Then(`request "Q1" completes with status 504`)
	s.And(`work "W1" is in state "orphaned"`)
	s.And(`work "W1" has a positive TTL of at most 5 seconds`)
	s.And(`the Redis key "work:W1" is gone`)
	s.And(`replying to work "W1" returns status 409`)
	s.And(`the response names error "unknown_work"`)
	s.And(`the Redis key "reply:W1" is gone`)
	s.Done()
}
