//go:build bdd

// Code generated by `true-bdd build tests`. DO NOT EDIT.
//
// Source: docs/scenarios.yaml
//
// One Go test per registry scenario, with the scenario's steps stated
// literally: what a reader sees here is what the machine runs. Done
// checks these steps against the registry before running any of them,
// so a hand edit to either side fails the test rather than quietly
// making the two documents disagree.
//
// Scenarios sharing a `path:` are written here in id order, so an
// inserted scenario lands where a reader expects it instead of at the
// end. Sequential by design — the suite's harness is shared.

package bddweb_test

import (
	"testing"

	"github.com/ondatra-ai/true-bdd/tests/bdd-web/scenarios"
)

// E2E-120: Choosing a section on the rail docks that section's tree, marks the rail entry current, and moves the URL to it
func TestE2E120(t *testing.T) {
	s := scenarios.New(t, "E2E-120")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.When(`the Product Owner clicks rail-item[section=architecture]`)
	s.Then(`the page shows sidebar-section[section=architecture]`)
	s.And(`the page does not show sidebar-section[section=product]`)
	s.And(`rail-item[section=architecture] has attribute "aria-current" = "page"`)
	s.And(`the URL ends with "/architecture"`)
	s.And(`the route is served by an App Router module`)
	s.Done()
}

// E2E-121: Hovering a rail entry previews that section's tree without leaving the page
func TestE2E121(t *testing.T) {
	s := scenarios.New(t, "E2E-121")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner hovers rail-item[section=product]`)
	s.Then(`the page shows rail-flyout`)
	s.And(`the page shows rail-flyout > sidebar-group[group=Stories]`)
	s.And(`the URL ends with "/architecture"`)
	s.Done()
}

// E2E-122: Choosing a row inside the rail's preview navigates to it and docks the section it belongs to
func TestE2E122(t *testing.T) {
	s := scenarios.New(t, "E2E-122")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner hovers rail-item[section=product]`)
	s.And(`the Product Owner clicks rail-flyout > story-row`)
	s.Then(`the URL contains "/product/stories/"`)
	s.And(`the page does not show rail-flyout`)
	s.And(`the page shows sidebar-section[section=product]`)
	s.And(`rail-item[section=product] has attribute "aria-current" = "page"`)
	s.Done()
}

// E2E-123: Home docks and renders its landing
func TestE2E123(t *testing.T) {
	s := scenarios.New(t, "E2E-123")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks rail-item[section=home]`)
	s.Then(`rail-item[section=home] has attribute "aria-current" = "page"`)
	s.And(`the URL ends with "/home"`)
	s.And(`the page shows home-landing`)
	s.Done()
}

// E2E-124: Builds docks and renders its landing, and carries no file editor because it is navigation only
func TestE2E124(t *testing.T) {
	s := scenarios.New(t, "E2E-124")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks rail-item[section=builds]`)
	s.Then(`rail-item[section=builds] has attribute "aria-current" = "page"`)
	s.And(`the URL ends with "/builds"`)
	s.And(`the page shows builds-landing`)
	s.But(`the page shows exactly 0 file-view`)
	s.Done()
}

// E2E-125: Scenarios live under Product
func TestE2E125(t *testing.T) {
	s := scenarios.New(t, "E2E-125")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`the page shows sidebar-section[section=product] > sidebar-group[group=Scenarios]`)
	s.And(`the page shows sidebar-section[section=product] > scenario-row`)
	s.Done()
}

// E2E-126: Builds carries none of the scenarios, because they belong to Product
func TestE2E126(t *testing.T) {
	s := scenarios.New(t, "E2E-126")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "builds"`)
	s.Then(`the page shows sidebar-section[section=builds]`)
	s.And(`the page shows exactly 0 sidebar-section[section=builds] > scenario-row`)
	s.Done()
}

// E2E-127: A sidebar group's caret appears only on hover and collapses the group where it stands
func TestE2E127(t *testing.T) {
	s := scenarios.New(t, "E2E-127")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner hovers sidebar-group[group=Features]`)
	s.And(`the Product Owner clicks sidebar-group[group=Features] > sidebar-caret`)
	s.Then(`sidebar-group[group=Features] > sidebar-caret has attribute "data-expanded" = "false"`)
	s.And(`the page does not show sidebar-group[group=Features] > sidebar-group-body`)
	s.And(`the URL did not change`)
	s.Done()
}

// E2E-128: A sidebar group's name navigates, so the row carries two targets and each does its own thing
func TestE2E128(t *testing.T) {
	s := scenarios.New(t, "E2E-128")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks sidebar-group[group=Features] > sidebar-group-name`)
	s.Then(`the URL ends with "/product/features"`)
	s.Done()
}

// E2E-129: A collapsed sidebar group stays collapsed across a section change and back
func TestE2E129(t *testing.T) {
	s := scenarios.New(t, "E2E-129")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.And(`the Product Owner has collapsed sidebar-group[group=Stories]`)
	s.When(`the Product Owner clicks rail-item[section=architecture]`)
	s.And(`the Product Owner clicks rail-item[section=product]`)
	s.Then(`sidebar-group[group=Stories] > sidebar-caret has attribute "data-expanded" = "false"`)
	s.Done()
}

// E2E-130: The sidebar row for the open page is highlighted, and the highlight moves when the page does
func TestE2E130(t *testing.T) {
	s := scenarios.New(t, "E2E-130")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "story 60.2" open`)
	s.When(`the Product Owner opens the workspace "scenarios"`)
	s.Then(`story-row[story-id=60.2] has attribute "data-selected" = "false"`)
	s.And(`sidebar-group[group=Scenarios] > sidebar-group-name has attribute "data-selected" = "true"`)
	s.Done()
}

// E2E-131: The architecture document renders as one file page carrying its path, a gutter line per buffer line, and the file's own content
func TestE2E131(t *testing.T) {
	s := scenarios.New(t, "E2E-131")
	s.Given(`the workspace is connected`)
	s.And(`a unique token is seeded into "docs/architecture/architecture.yaml"`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`file-view-path has text "docs/architecture/architecture.yaml"`)
	s.And(`file-view-editor contains text "services:"`)
	s.And(`file-view-editor contains the seeded token`)
	s.And(`the page shows one file-view-gutter-line per line of "docs/architecture/architecture.yaml"`)
	s.But(`the page offers no per-entity form page`)
	s.Done()
}

// E2E-132: Focusing the editor changes no background, border, outline or shadow and reflows no text, because editing happens in place
func TestE2E132(t *testing.T) {
	s := scenarios.New(t, "E2E-132")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks file-view-editor`)
	s.Then(`file-view-editor has computed "background-color" = "rgba(0, 0, 0, 0)"`)
	s.And(`file-view-editor's background, border, outline and shadow are unchanged`)
	s.And(`file-view-editor did not move within file-view`)
	s.Done()
}

// E2E-133: The architecture outline lists one row per service with flat terms and the compose path
func TestE2E133(t *testing.T) {
	s := scenarios.New(t, "E2E-133")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows exactly 2 sidebar-group[group=Services] > arch-service-row`)
	s.And(`the page shows arch-service-row[service=mcp-service]`)
	s.And(`the page shows arch-service-row[service=postgres]`)
	s.And(`the page shows sidebar-group[group=Terms] > arch-term-row`)
	s.And(`sidebar-group[group=Docker] > arch-docker-row matches docker-compose\.yml`)
	s.Done()
}

// E2E-134: A service's derived details belong to that service alone, so what one declares never renders under another
func TestE2E134(t *testing.T) {
	s := scenarios.New(t, "E2E-134")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows arch-service-details[service=mcp-service] > service-tech[tech=go]`)
	s.And(`arch-service-details[service=mcp-service] > service-docker-provenance contains text "services/mcp/Dockerfile"`)
	s.And(`arch-service-details[service=postgres] > service-docker-provenance contains text "docker-compose.yml#services.postgres"`)
	s.But(`the page shows exactly 0 arch-service-details[service=postgres] > service-tech[tech=go]`)
	s.Done()
}

// E2E-135: Declaring a service in the editor adds its outline row live
func TestE2E135(t *testing.T) {
	s := scenarios.New(t, "E2E-135")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner declares a "redis" service in the editor`)
	s.Then(`the page shows arch-service-row[service=redis]`)
	s.And(`the page shows exactly 3 sidebar-group[group=Services] > arch-service-row`)
	s.Done()
}

// E2E-136: Removing a service from the editor takes its outline row away again, so the outline is derived rather than accumulated
func TestE2E136(t *testing.T) {
	s := scenarios.New(t, "E2E-136")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has declared a "redis" service in the editor`)
	s.When(`the Product Owner restores the original buffer in the editor`)
	s.Then(`the page shows exactly 0 arch-service-row[service=redis]`)
	s.And(`the page shows exactly 2 sidebar-group[group=Services] > arch-service-row`)
	s.Done()
}

// E2E-137: An outline entry scrolls the file to that entry's own line
func TestE2E137(t *testing.T) {
	s := scenarios.New(t, "E2E-137")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks arch-service-row[service=postgres]`)
	s.Then(`the page shows file-view-flash`)
	s.And(`file-view-flash marks the line matching ^ {2}postgres: in "docs/architecture/architecture.yaml"`)
	s.Done()
}

// E2E-138: An outline entry near the end of a file scrolls as far as the file goes, rather than past it
func TestE2E138(t *testing.T) {
	s := scenarios.New(t, "E2E-138")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks sidebar-group[group=Docker] > arch-docker-row`)
	s.Then(`file-view-editor is scrolled to its end`)
	s.Done()
}

// E2E-139: An outline entry reached from another page navigates first and scrolls to the line after
func TestE2E139(t *testing.T) {
	s := scenarios.New(t, "E2E-139")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "story 60.2" open`)
	s.When(`the Product Owner hovers rail-item[section=architecture]`)
	s.And(`the Product Owner clicks rail-flyout > arch-service-row[service=postgres]`)
	s.Then(`the URL ends with "/architecture"`)
	s.And(`file-view-flash marks the line matching ^ {2}postgres: in "docs/architecture/architecture.yaml"`)
	s.Done()
}

// E2E-140: Endpoints belong to the service that serves them and connection details to the one that is connected to
func TestE2E140(t *testing.T) {
	s := scenarios.New(t, "E2E-140")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page shows arch-service-details[service=mcp-service] > service-endpoint[method=POST][path=/mcp]`)
	s.And(`the page shows exactly 0 arch-service-details[service=mcp-service] > service-connection`)
	s.And(`arch-service-details[service=postgres] > service-connection[key=port] contains text "5432"`)
	s.And(`the page shows exactly 0 arch-service-details[service=postgres] > service-endpoint`)
	s.Done()
}

// E2E-141: An endpoint declared in the editor reaches the derived view and the file alike
func TestE2E141(t *testing.T) {
	s := scenarios.New(t, "E2E-141")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner declares a uniquely-named endpoint for "mcp-service" in the editor`)
	s.Then(`the page shows the new endpoint under arch-service-details[service=mcp-service]`)
	s.And(`"docs/architecture/architecture.yaml" lists the new endpoint under the "mcp-service" service`)
	s.Done()
}

// E2E-142: An edit is saved by the CLI that owns the folder, proven by the file on disk and by a receipt the relay and the browser both saw for the same work
func TestE2E142(t *testing.T) {
	s := scenarios.New(t, "E2E-142")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner adds a uniquely-named term in the editor`)
	s.Then(`save-state has attribute "data-save-state" = "saved"`)
	s.And(`"docs/architecture/architecture.yaml" holds the new term under its "terms" node`)
	s.And(`the browser's write receipt names that path and the file's hash`)
	s.And(`the relay's audit holds the CLI's receipt for the same work, revision and hash`)
	s.Done()
}

// E2E-143: An edit survives a reload, because the page reads the document rather than remembering it
func TestE2E143(t *testing.T) {
	s := scenarios.New(t, "E2E-143")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has added a uniquely-named term in the editor`)
	s.When(`the Product Owner reloads the page`)
	s.Then(`file-view-editor contains the new term`)
	s.Done()
}

// E2E-144: An edit survives a relay restart, because the document lives with the CLI and not with the relay
func TestE2E144(t *testing.T) {
	s := scenarios.New(t, "E2E-144")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has added a uniquely-named term in the editor`)
	s.When(`the relay restarts`)
	s.And(`the Product Owner reloads the page`)
	s.Then(`file-view-editor contains the new term`)
	s.And(`"docs/architecture/architecture.yaml" holds the new term under its "terms" node`)
	s.Done()
}

// E2E-145: A buffer that does not parse is never sent, and the derived views hold their last valid reading
func TestE2E145(t *testing.T) {
	s := scenarios.New(t, "E2E-145")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner breaks the editor's YAML with an unterminated sequence`)
	s.Then(`save-state has attribute "data-save-state" matching invalid|rejected`)
	s.And(`the page shows yaml-invalid-indicator`)
	s.And(`the browser sent no write`)
	s.And(`no allowed document changed`)
	s.And(`the page shows exactly 2 sidebar-group[group=Services] > arch-service-row`)
	s.Done()
}

// E2E-146: Correcting a buffer that did not parse lets the save and the derived views move on together
func TestE2E146(t *testing.T) {
	s := scenarios.New(t, "E2E-146")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has broken the editor's YAML with an unterminated sequence`)
	s.When(`the Product Owner declares a uniquely-named service in the editor`)
	s.Then(`the page does not show yaml-invalid-indicator`)
	s.And(`"docs/architecture/architecture.yaml" holds the new service`)
	s.And(`the page shows exactly 3 sidebar-group[group=Services] > arch-service-row`)
	s.Done()
}

// E2E-147: With no CLI connected a save reports the mapped failure and never claims to have saved
func TestE2E147(t *testing.T) {
	s := scenarios.New(t, "E2E-147")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the remote is stopped`)
	s.And(`the Product Owner appends a unique comment in the editor`)
	s.Then(`the session is not listed`)
	s.And(`the write returns status 404 or 504`)
	s.And(`the response names the error its status maps to`)
	s.And(`save-state does not have attribute "data-save-state" = "saved"`)
	s.And(`no allowed document changed`)
	s.Done()
}

// E2E-148: A CLI that dies after accepting a write either completes it with a full receipt or reports the failure, and never reports a success it cannot evidence
func TestE2E148(t *testing.T) {
	s := scenarios.New(t, "E2E-148")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner appends a unique comment in the editor`)
	s.And(`the remote is stopped once the write is in flight`)
	s.Then(`the write returns status 200, 404 or 504`)
	s.And(`a successful write carries a receipt naming the path, the file's hash and a work id`)
	s.And(`a successful write's receipt is corroborated by the relay's audit for the same work`)
	s.And(`a failed write leaves save-state short of "saved"`)
	s.Done()
}

// E2E-149: The PRD, the features file, a story and the registry each render as their own file page carrying that file's content
func TestE2E149(t *testing.T) {
	s := scenarios.New(t, "E2E-149")
	s.Given(`the workspace is connected`)
	s.And(`a unique token is seeded into each product document`)
	s.When(`the Product Owner opens each product document in turn`)
	s.Then(`every product document's page names that document in file-view-path`)
	s.And(`every product document's page shows that document's seeded token`)
	s.Done()
}

// E2E-150: The Product outline holds its four groups in order with a row per entry
func TestE2E150(t *testing.T) {
	s := scenarios.New(t, "E2E-150")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`the page shows exactly 4 sidebar-section[section=product] > sidebar-group`)
	s.And(`the sidebar groups read "PRD", "Features", "Stories", "Scenarios"`)
	s.And(`the page shows exactly 3 sidebar-group[group=Stories] > story-row`)
	s.And(`the page shows exactly 3 sidebar-group[group=Features] > feature-row`)
	s.And(`the page shows exactly 5 sidebar-group[group=Scenarios] > scenario-row`)
	s.Done()
}

// E2E-151: A feature's own row leads to what is gathered under it, which is not where its group header leads
func TestE2E151(t *testing.T) {
	s := scenarios.New(t, "E2E-151")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks feature-row[feature=summaries]`)
	s.Then(`the URL ends with "/product/features/summaries"`)
	s.Done()
}

// E2E-152: A story created through the form appears in the outline without a reload
func TestE2E152(t *testing.T) {
	s := scenarios.New(t, "E2E-152")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner creates a story titled "Live added story" under the feature "summaries"`)
	s.Then(`the page shows exactly 4 sidebar-group[group=Stories] > story-row`)
	s.Done()
}

// E2E-153: A scenario typed into the registry appears in the outline without a reload
func TestE2E153(t *testing.T) {
	s := scenarios.New(t, "E2E-153")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "scenarios" open`)
	s.When(`the Product Owner types a uniquely-named scenario into the editor`)
	s.Then(`the page shows the new scenario's scenario-row`)
	s.Done()
}

// E2E-154: Stories are flat siblings of one another, and nothing in the workspace speaks of epics
func TestE2E154(t *testing.T) {
	s := scenarios.New(t, "E2E-154")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`the page shows exactly 3 sidebar-group[group=Stories] > story-row`)
	s.And(`every story row shares one parent`)
	s.And(`the page shows exactly 0 elements whose testid begins "epic"`)
	s.Done()
}

// E2E-155: The features file the workspace serves carries only an id and a description per feature, and the stories and scenarios it serves carry their feature reference
func TestE2E155(t *testing.T) {
	s := scenarios.New(t, "E2E-155")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "features"`)
	s.Then(`every feature the served file holds has exactly the keys "description" and "id"`)
	s.And(`the served story "60.2" has a feature`)
	s.And(`the served scenario "E2E-601" has a feature`)
	s.Done()
}

// E2E-156: A feature page gathers the stories and requirements tagged to it
func TestE2E156(t *testing.T) {
	s := scenarios.New(t, "E2E-156")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "feature summaries"`)
	s.Then(`feature-description holds the description of "summaries"`)
	s.And(`the page shows feature-stories-list > feature-story-row[story-id=60.1]`)
	s.And(`the page shows feature-stories-list > feature-story-row[story-id=60.2]`)
	s.And(`the page shows feature-scenarios-list > feature-scenario-row[scenario-id=E2E-601]`)
	s.Done()
}

// E2E-157: Re-tagging a story through its row's picker writes the choice to the story and takes the row out of the gathering it left
func TestE2E157(t *testing.T) {
	s := scenarios.New(t, "E2E-157")
	s.Given(`the workspace is connected`)
	s.And(`a unique feature is seeded into the product's features`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.When(`the Product Owner picks the seeded feature in feature-story-row[story-id=60.1]`)
	s.Then(`the page shows exactly 0 feature-stories-list > feature-story-row[story-id=60.1]`)
	s.And(`the story "docs/product/stories/60.1-summary-length-preference.yaml" has the seeded feature`)
	s.Done()
}

// E2E-158: Re-tagging a story by hand in its own document takes its row out of the gathering just as the picker does
func TestE2E158(t *testing.T) {
	s := scenarios.New(t, "E2E-158")
	s.Given(`the workspace is connected`)
	s.And(`a unique feature is seeded into the product's features`)
	s.And(`the Product Owner has the workspace "story 60.2" open`)
	s.When(`the Product Owner replaces the story's feature with the seeded one in the editor`)
	s.And(`the Product Owner opens the workspace "feature summaries"`)
	s.Then(`the story "docs/product/stories/60.2-summary-shared-docs.yaml" has the seeded feature`)
	s.And(`the page shows exactly 0 feature-stories-list > feature-story-row[story-id=60.2]`)
	s.Done()
}

// E2E-159: The PRD and the features file are editable in place like any other document, and what is typed there persists as valid YAML
func TestE2E159(t *testing.T) {
	s := scenarios.New(t, "E2E-159")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner appends a unique comment to the PRD and to the features file in turn`)
	s.Then(`every edited document's editor shows its comment`)
	s.And(`every edited document holds its comment on disk`)
	s.And(`every edited document still parses`)
	s.Done()
}

// E2E-160: A new story cannot be created without a feature, because a story nothing gathers is a story nobody finds
func TestE2E160(t *testing.T) {
	s := scenarios.New(t, "E2E-160")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.And(`the Product Owner has opened the new-story form`)
	s.When(`the Product Owner fills new-story-title with "Story without a feature"`)
	s.And(`the Product Owner clicks new-story-submit`)
	s.Then(`no allowed document changed`)
	s.And(`the page shows new-story-form`)
	s.And(`the page shows exactly 3 sidebar-group[group=Stories] > story-row`)
	s.Done()
}

// E2E-161: The feature picker filters as it is typed, so a long list stays usable and a static one would fail
func TestE2E161(t *testing.T) {
	s := scenarios.New(t, "E2E-161")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.And(`the Product Owner has opened the new-story form`)
	s.When(`the Product Owner clicks feature-picker-toggle`)
	s.And(`the Product Owner fills feature-picker-input with "error"`)
	s.Then(`the page shows feature-picker-option[feature=error-handling]`)
	s.And(`the page shows exactly 0 feature-picker-option[feature=summaries]`)
	s.Done()
}

// E2E-162: A story created against an existing feature is written carrying it
func TestE2E162(t *testing.T) {
	s := scenarios.New(t, "E2E-162")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.And(`the Product Owner has opened the new-story form`)
	s.When(`the Product Owner creates a story titled "A story that names its feature" under the feature "error-handling"`)
	s.Then(`exactly 1 file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the created story has feature "error-handling"`)
	s.Done()
}

// E2E-163: Creating a novel feature while creating a story writes an id-and-description stub beside the story that uses it
func TestE2E163(t *testing.T) {
	s := scenarios.New(t, "E2E-163")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.And(`the Product Owner has opened the new-story form`)
	s.When(`the Product Owner creates a story titled "Story with a fresh feature" under a uniquely-named new feature`)
	s.Then(`"docs/product/features.yaml" holds the new feature with exactly the keys "description" and "id"`)
	s.And(`exactly 1 file matching "docs/product/stories/*.yaml" is created`)
	s.And(`the created story has the new feature`)
	s.Done()
}

// E2E-164: Changing a story's feature through its picker writes the choice into that story's own document
func TestE2E164(t *testing.T) {
	s := scenarios.New(t, "E2E-164")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "story 60.2" open`)
	s.When(`the Product Owner picks the feature "error-handling" in feature-picker`)
	s.Then(`the story "docs/product/stories/60.2-summary-shared-docs.yaml" has feature "error-handling"`)
	s.Done()
}

// E2E-165: A requirement with no feature waits in the unaligned bucket, and tagging it there writes the feature onto its own registry entry
func TestE2E165(t *testing.T) {
	s := scenarios.New(t, "E2E-165")
	s.Given(`the workspace is connected`)
	s.And(`a unique feature is seeded into the product's features`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.When(`the Product Owner picks the seeded feature in unaligned-scenario-row[scenario-id=INT-901]`)
	s.Then(`the scenario "INT-901" in "docs/scenarios.yaml" has the seeded feature`)
	s.And(`the page shows exactly 0 unaligned-bucket > unaligned-scenario-row[scenario-id=INT-901]`)
	s.Done()
}

// E2E-166: A requirement pointing at a feature that does not exist is surfaced as dangling, naming the reference it could not resolve
func TestE2E166(t *testing.T) {
	s := scenarios.New(t, "E2E-166")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "feature summaries"`)
	s.Then(`the page shows unaligned-bucket > unaligned-scenario-row[scenario-id=E2E-604]`)
	s.And(`unaligned-scenario-row[scenario-id=E2E-604] has attribute "data-dangling" = "true"`)
	s.And(`unaligned-scenario-row[scenario-id=E2E-604] has attribute "data-dangling-ref" = "ghost"`)
	s.Done()
}

// E2E-167: The chat docks in the layout rather than over it, narrowing the content
func TestE2E167(t *testing.T) {
	s := scenarios.New(t, "E2E-167")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page shows chat-dock-panel`)
	s.And(`content-pane is narrower than it was`)
	s.And(`content-pane ends at or before chat-dock-panel begins`)
	s.And(`chat-dock-panel has computed "position" other than "fixed"`)
	s.Done()
}

// E2E-168: The chat collapses back to a thin tab, so the reader can always get the space back
func TestE2E168(t *testing.T) {
	s := scenarios.New(t, "E2E-168")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner clicks chat-dock-toggle`)
	s.Then(`the page does not show chat-dock-panel`)
	s.And(`the page shows chat-dock-toggle`)
	s.Done()
}

// E2E-169: One conversation belongs to the workspace and follows the reader from page to page
func TestE2E169(t *testing.T) {
	s := scenarios.New(t, "E2E-169")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner sends a uniquely-marked chat message`)
	s.And(`the Product Owner clicks rail-item[section=product]`)
	s.And(`the Product Owner clicks story-row[story-id=60.2]`)
	s.Then(`the URL contains "/product/stories/"`)
	s.And(`chat-dock-history contains the chat marker`)
	s.Done()
}

// E2E-170: Chat edits the document the reader is looking at and proves it with the same receipt a typed edit does
func TestE2E170(t *testing.T) {
	s := scenarios.New(t, "E2E-170")
	s.Given(`the workspace is connected with the deterministic chat driver`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner asks the chat to add a uniquely-named term`)
	s.Then(`file-view-editor contains the new term`)
	s.And(`the page shows the new term's arch-term-row`)
	s.And(`"docs/architecture/architecture.yaml" holds the new term under its "terms" node`)
	s.And(`the browser's write receipt names that path and the file's hash`)
	s.And(`the relay's audit holds the CLI's receipt for the same work, revision and hash`)
	s.Done()
}

// E2E-171: On a page that is not a document the chat answers without writing anything, because there is nothing there to edit
func TestE2E171(t *testing.T) {
	s := scenarios.New(t, "E2E-171")
	s.Given(`the workspace is connected with the deterministic chat driver`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner asks the chat to add a uniquely-named term`)
	s.Then(`the chat answered`)
	s.And(`no allowed document changed`)
	s.And(`the browser sent no write`)
	s.Done()
}

// E2E-172: On the workspace's own landing the chat answers without writing anything either
func TestE2E172(t *testing.T) {
	s := scenarios.New(t, "E2E-172")
	s.Given(`the workspace is connected with the deterministic chat driver`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner asks the chat to add a uniquely-named term`)
	s.Then(`the chat answered`)
	s.And(`no allowed document changed`)
	s.And(`the browser sent no write`)
	s.Done()
}

// E2E-173: Dragging the chat divider resizes the panel by the distance dragged
func TestE2E173(t *testing.T) {
	s := scenarios.New(t, "E2E-173")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "architecture" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner drags chat-dock-resizer 120 pixels left`)
	s.Then(`chat-dock-panel is 120 pixels wider than it was, within 24 pixels`)
	s.Done()
}

// E2E-174: A scenario the chat adds appears in the outline and is written by the chat's own save
func TestE2E174(t *testing.T) {
	s := scenarios.New(t, "E2E-174")
	s.Given(`the workspace is connected with the deterministic chat driver`)
	s.And(`the Product Owner has the workspace "scenarios" open`)
	s.And(`the Product Owner has opened the chat`)
	s.When(`the Product Owner asks the chat to add a uniquely-named scenario`)
	s.Then(`the page shows the new scenario's scenario-row`)
	s.And(`"docs/scenarios.yaml" holds the new scenario`)
	s.And(`the browser's write receipt names that path and the file's hash`)
	s.Done()
}

// E2E-175: The overview names itself and carries the session's folder and id in its metadata line
func TestE2E175(t *testing.T) {
	s := scenarios.New(t, "E2E-175")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`overview-title contains text "Workspace overview"`)
	s.And(`overview-meta contains the session's folder`)
	s.And(`overview-meta contains the session's id`)
	s.Done()
}

// E2E-176: The overview's three actions are offered, and none is gated while the session has no run of its own
func TestE2E176(t *testing.T) {
	s := scenarios.New(t, "E2E-176")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`overview-action-build-tests is enabled`)
	s.And(`overview-action-build-code is enabled`)
	s.And(`overview-action-refresh is enabled`)
	s.Done()
}

// E2E-177: Refresh reads the session rather than starting anything, because reading is not a mutation
func TestE2E177(t *testing.T) {
	s := scenarios.New(t, "E2E-177")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.When(`the Product Owner clicks overview-action-refresh`)
	s.Then(`the page issued a session detail read`)
	s.Done()
}

// E2E-178: Each build action dispatches the command it is named for
func TestE2E178(t *testing.T) {
	s := scenarios.New(t, "E2E-178")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.When(`the Product Owner clicks overview-action-build-tests`)
	s.Then(`the page dispatched the command "build-tests"`)
	s.Done()
}

// E2E-179: The second build action dispatches its own command and not the first one's
func TestE2E179(t *testing.T) {
	s := scenarios.New(t, "E2E-179")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.When(`the Product Owner clicks overview-action-build-code`)
	s.Then(`the page dispatched the command "build-code"`)
	s.Done()
}

// E2E-180: An active run of the session's own disables its build actions and leaves Refresh available, because reading is never gated by running
func TestE2E180(t *testing.T) {
	s := scenarios.New(t, "E2E-180")
	s.Given(`the workspace is connected`)
	s.And(`the session reports an active run of its own`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`overview-action-build-tests is disabled`)
	s.And(`overview-action-build-code is disabled`)
	s.But(`overview-action-refresh is enabled`)
	s.Done()
}

// E2E-181: The inventory-health list renders a row and a status chip for every entry the session reports, files, directories and checklists alike
func TestE2E181(t *testing.T) {
	s := scenarios.New(t, "E2E-181")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-inventory`)
	s.And(`every inventory entry has a row with a chip carrying a known status`)
	s.And(`overview-inventory-row[key=architecture] contains text "docs/architecture/architecture.yaml"`)
	s.And(`overview-inventory-row[key=architecture] > overview-inventory-chip has attribute "data-status" = "present"`)
	s.And(`overview-inventory-row[key=stories-dir] contains text "docs/product/stories"`)
	s.And(`overview-inventory-row[key=stories-dir] > overview-inventory-chip has attribute "data-status" = "present"`)
	s.Done()
}

// E2E-182: A clean read renders no degraded banner at all, because an absent state must render nothing rather than a reassurance
func TestE2E182(t *testing.T) {
	s := scenarios.New(t, "E2E-182")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-title`)
	s.And(`the page shows overview-inventory`)
	s.But(`the page shows exactly 0 overview-banner`)
	s.Done()
}

// E2E-183: An inventory the session could not fit renders as its own bordered banner
func TestE2E183(t *testing.T) {
	s := scenarios.New(t, "E2E-183")
	s.Given(`the workspace is connected`)
	s.And(`the session reports a truncated inventory`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-banner[kind=inventory_truncated]`)
	s.Done()
}

// E2E-184: A sibling owner working the same folder renders as its own bordered banner
func TestE2E184(t *testing.T) {
	s := scenarios.New(t, "E2E-184")
	s.Given(`the workspace is connected`)
	s.And(`the session reports a same-project sibling owner`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-banner[kind=folder_conflict]`)
	s.Done()
}

// E2E-185: An architectural spec found somewhere other than its canonical path renders as its own bordered banner
func TestE2E185(t *testing.T) {
	s := scenarios.New(t, "E2E-185")
	s.Given(`the workspace is connected`)
	s.And(`the session reports an architecture path divergence`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`the page shows overview-banner[kind=path_mismatch]`)
	s.Done()
}

// E2E-186: The overview's breadcrumb is a two-level trail leading back to the sessions list
func TestE2E186(t *testing.T) {
	s := scenarios.New(t, "E2E-186")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "home"`)
	s.Then(`content-breadcrumb holds a "Sessions" link to "/"`)
	s.And(`content-breadcrumb's current crumb has text "Workspace overview"`)
	s.Done()
}

// E2E-187: A successful dispatch re-reads the session, so the build actions reflect the run it just started without waiting to be refreshed
func TestE2E187(t *testing.T) {
	s := scenarios.New(t, "E2E-187")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "home" open`)
	s.And(`overview-action-build-tests is enabled`)
	s.When(`the Product Owner clicks overview-action-build-tests`)
	s.Then(`the page issued a session detail read`)
	s.And(`overview-action-build-tests is disabled`)
	s.And(`overview-action-build-code is disabled`)
	s.Done()
}

// E2E-188: The Product sidebar carries the brand, its workspace context beneath it, an underlined section header, and the open file highlighted
func TestE2E188(t *testing.T) {
	s := scenarios.New(t, "E2E-188")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`sidebar-brand contains text "TrueBDD"`)
	s.And(`sidebar-brand-meta is non-empty`)
	s.And(`sidebar-brand-meta sits below the brand name`)
	s.And(`sidebar-section-header matches 02\s*[—-]\s*PRODUCT`)
	s.And(`sidebar-section-header is underlined`)
	s.And(`prd-row has attribute "data-selected" = "true"`)
	s.Done()
}

// E2E-189: The new-story control lives in the tree it adds to, and opens the form from there
func TestE2E189(t *testing.T) {
	s := scenarios.New(t, "E2E-189")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner clicks sidebar-group[group=Stories] > new-story-open`)
	s.Then(`the page shows new-story-form`)
	s.Done()
}

// E2E-190: Every rail entry pairs an icon with its full word in small caps, the icon leading
func TestE2E190(t *testing.T) {
	s := scenarios.New(t, "E2E-190")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`every rail item shows an icon glyph`)
	s.And(`every rail item shows its full label`)
	s.And(`every rail label has computed "text-transform" = "uppercase"`)
	s.And(`every rail label is letter-spaced from the token "--ls-label"`)
	s.And(`every rail icon sits above or before its label`)
	s.Done()
}

// E2E-191: The current rail entry is an inverted tile, distinct from its neighbours and from the rail it sits on
func TestE2E191(t *testing.T) {
	s := scenarios.New(t, "E2E-191")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`rail-item[section=product] has attribute "aria-current" = "page"`)
	s.And(`rail-item[section=product] resolves "background-color" from the token "--surface-page"`)
	s.And(`rail-item[section=product] resolves "color" from the token "--text-primary"`)
	s.And(`rail-item[section=product]'s background differs from rail-item[section=architecture]'s`)
	s.And(`rail-item[section=product] does not resolve "background-color" from the token "--surface-inverse"`)
	s.Done()
}

// E2E-192: The way back to the sessions list is a link pinned at the foot of the rail
func TestE2E192(t *testing.T) {
	s := scenarios.New(t, "E2E-192")
	s.Given(`the workspace is connected`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`rail-utilities holds a sessions link`)
	s.And(`rail-utilities sits in the lower part of rail`)
	s.Done()
}

// E2E-193: The product landing renders its document as a file card — a kicker above a title above a muted subtitle, then a header bar naming the path and counting the lines
func TestE2E193(t *testing.T) {
	s := scenarios.New(t, "E2E-193")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "product"`)
	s.Then(`the page renders the file card of "docs/product/product.yaml" titled "product.yaml"`)
	s.And(`file-view-kicker matches 02\s*[—-]\s*PRODUCT`)
	s.Done()
}

// E2E-194: The architecture page renders the same file card under its own section's kicker, because the header block belongs to every section
func TestE2E194(t *testing.T) {
	s := scenarios.New(t, "E2E-194")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "architecture"`)
	s.Then(`the page renders the file card of "docs/architecture/architecture.yaml" titled "architecture.yaml"`)
	s.And(`file-view-kicker matches (?i)01\s*[—-]\s*Architecture`)
	s.Done()
}

// E2E-195: An edit on a file card round-trips, so the card is a document and not a picture of one
func TestE2E195(t *testing.T) {
	s := scenarios.New(t, "E2E-195")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "product" open`)
	s.When(`the Product Owner appends a unique comment in the editor`)
	s.Then(`save-state has attribute "data-save-state" = "saved"`)
	s.And(`"docs/product/product.yaml" holds the comment`)
	s.And(`"docs/product/product.yaml" still parses`)
	s.Done()
}

// E2E-196: A story page carries its kicker, its title built from the story's own id and title, and the deep breadcrumb trail
func TestE2E196(t *testing.T) {
	s := scenarios.New(t, "E2E-196")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "story 60.1"`)
	s.Then(`file-view-kicker matches 02\s*[—-]\s*PRODUCT\s*/\s*60\.1`)
	s.And(`file-view-title names the story's id and title`)
	s.And(`content-breadcrumb's crumbs read "Sessions", "Workspace overview", "Product", "60.1-summary-length-preference.yaml"`)
	s.And(`content-breadcrumb's current crumb has text "60.1-summary-length-preference.yaml"`)
	s.Done()
}

// E2E-197: A story's Feature pill is built of three named parts and hides its picker until it is asked for
func TestE2E197(t *testing.T) {
	s := scenarios.New(t, "E2E-197")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "story 60.1" open`)
	s.Then(`feature-picker-toggle > feature-pill-label matches (?i)feature:`)
	s.And(`feature-picker-toggle > feature-pill-value holds the story's feature`)
	s.And(`feature-picker-toggle > feature-pill-change matches (?i)change`)
	s.And(`the page does not show feature-picker-input`)
	s.Done()
}

// E2E-198: A story's Feature pill is operable rather than decorative, writing what is picked to the document
func TestE2E198(t *testing.T) {
	s := scenarios.New(t, "E2E-198")
	s.Given(`the workspace is connected`)
	s.And(`a unique feature is seeded into the product's features`)
	s.And(`the Product Owner has the workspace "story 60.1" open`)
	s.When(`the Product Owner clicks feature-picker-toggle`)
	s.And(`the Product Owner picks the seeded feature in feature-picker`)
	s.Then(`the page shows feature-picker-input`)
	s.And(`the story "docs/product/stories/60.1-summary-length-preference.yaml" has the seeded feature`)
	s.Done()
}

// E2E-199: The features page renders its document as a file card of its own
func TestE2E199(t *testing.T) {
	s := scenarios.New(t, "E2E-199")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "features"`)
	s.Then(`the page renders the file card of "docs/product/features.yaml" titled "features.yaml"`)
	s.And(`file-view-kicker matches 02\s*[—-]\s*PRODUCT\s*/\s*FEATURES`)
	s.Done()
}

// E2E-200: The scenarios page is a table with one row per registry entry, each row carrying its id as a link, its description, its service, and its story where one is linked
func TestE2E200(t *testing.T) {
	s := scenarios.New(t, "E2E-200")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "scenarios"`)
	s.Then(`the page shows scenario-table`)
	s.And(`the page holds a heading matching Requirements\s*/\s*Scenarios`)
	s.And(`the page holds the text "flat registry"`)
	s.And(`scenario-table's columns read "scenario", "description", "service", "linked story"`)
	s.And(`the page shows one scenario-table-row per entry of "docs/scenarios.yaml"`)
	s.And(`every row's scenario-id-link is a link carrying that row's id`)
	s.And(`every row's description and service cells hold the registry's values`)
	s.And(`every row with a linked story links to it by the story's own id`)
	s.And(`every row without a linked story shows no linked-story link`)
	s.Done()
}

// E2E-201: A story route naming nothing renders a not-found body inside the shell under the generic trail, rather than crashing or claiming a document
func TestE2E201(t *testing.T) {
	s := scenarios.New(t, "E2E-201")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "story 99.9"`)
	s.Then(`the page holds text matching story\s*99\.9\s*not found`)
	s.And(`content-breadcrumb's links read "Home", "Product"`)
	s.And(`content-breadcrumb contains text "Stories"`)
	s.But(`content-breadcrumb does not contain text "Workspace overview"`)
	s.And(`content-breadcrumb's current crumb has text "99.9"`)
	s.Done()
}

// E2E-202: A feature page names itself with a kicker, its own id and the description its record carries
func TestE2E202(t *testing.T) {
	s := scenarios.New(t, "E2E-202")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "feature summaries"`)
	s.Then(`feature-page-kicker matches 02\s*[—-]\s*PRODUCT\s*/\s*FEATURES\s*/\s*SUMMARIES`)
	s.And(`the page's heading has text "summaries"`)
	s.And(`feature-description holds the description of "summaries"`)
	s.And(`feature-description resolves "color" from the token "--text-muted"`)
	s.And(`feature-description sits below the page's heading`)
	s.Done()
}

// E2E-203: A feature page gathers stories, requirements and the unaligned under three named sections, each row a linked title beside its picker
func TestE2E203(t *testing.T) {
	s := scenarios.New(t, "E2E-203")
	s.Given(`the workspace is connected`)
	s.When(`the Product Owner opens the workspace "feature summaries"`)
	s.Then(`the page holds the headings "User stories", "Requirements", "Unaligned requirements"`)
	s.And(`feature-story-row[story-id=60.1] links to its story page carrying its id and title`)
	s.And(`feature-scenario-row[scenario-id=E2E-601] links to the scenarios page carrying its id and description`)
	s.And(`unaligned-scenario-row[scenario-id=INT-901] links to the scenarios page carrying its id and description`)
	s.And(`unaligned-scenario-row[scenario-id=INT-901] > feature-pill-value matches (?i)\(none\)`)
	s.And(`feature-story-row[story-id=60.1] is a linked title left of its picker, sharing its row`)
	s.And(`feature-scenario-row[scenario-id=E2E-601] is a linked title left of its picker, sharing its row`)
	s.And(`unaligned-scenario-row[scenario-id=INT-901] is a linked title left of its picker, sharing its row`)
	s.Done()
}

// E2E-204: A requirement row's own picker re-tags it, so the two kinds of row are equally operable
func TestE2E204(t *testing.T) {
	s := scenarios.New(t, "E2E-204")
	s.Given(`the workspace is connected`)
	s.And(`a unique feature is seeded into the product's features`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.When(`the Product Owner picks the seeded feature in feature-scenario-row[scenario-id=E2E-601]`)
	s.Then(`the scenario "E2E-601" in "docs/scenarios.yaml" has the seeded feature`)
	s.And(`the page shows exactly 0 feature-scenarios-list > feature-scenario-row[scenario-id=E2E-601]`)
	s.Done()
}

// E2E-205: A requirement's title link lands on the registry at that requirement's own line
func TestE2E205(t *testing.T) {
	s := scenarios.New(t, "E2E-205")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.When(`the Product Owner clicks the link of feature-scenario-row[scenario-id=E2E-601]`)
	s.Then(`the URL ends with "/product/scenarios"`)
	s.And(`file-view-flash marks the line matching ^ {2}E2E-601: in "docs/scenarios.yaml"`)
	s.Done()
}

// E2E-206: An unaligned requirement's title link lands on its own line too, because the two rows are wired separately
func TestE2E206(t *testing.T) {
	s := scenarios.New(t, "E2E-206")
	s.Given(`the workspace is connected`)
	s.And(`the Product Owner has the workspace "feature summaries" open`)
	s.When(`the Product Owner clicks the link of unaligned-scenario-row[scenario-id=INT-901]`)
	s.Then(`the URL ends with "/product/scenarios"`)
	s.And(`file-view-flash marks the line matching ^ {2}INT-901: in "docs/scenarios.yaml"`)
	s.Done()
}

// E2E-207: The sessions list holds one row per connected session, inside the container that names it
func TestE2E207(t *testing.T) {
	s := scenarios.New(t, "E2E-207")
	s.Given(`the relay is running`)
	s.And(`two remotes are running in their own project trees`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page shows sessions-list`)
	s.And(`the page shows exactly 2 sessions-list > session-row`)
	s.And(`every connected session has its own row`)
	s.Done()
}

// E2E-208: A session's row states the folder it is in, the id it holds and the version it runs
func TestE2E208(t *testing.T) {
	s := scenarios.New(t, "E2E-208")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`session-row > session-folder has the session's folder`)
	s.And(`session-row > session-meta contains the session's id`)
	s.And(`session-row > session-version has the session's version`)
	s.Done()
}

// E2E-209: Every row's Open control is a link to that row's own workspace, never a shared one
func TestE2E209(t *testing.T) {
	s := scenarios.New(t, "E2E-209")
	s.Given(`the relay is running`)
	s.And(`two remotes are running in their own project trees`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`every session-open is an anchor`)
	s.And(`every session-open's href is its own row's workspace home`)
	s.Done()
}

// E2E-210: Following a row's Open control lands in that session's workspace
func TestE2E210(t *testing.T) {
	s := scenarios.New(t, "E2E-210")
	s.Given(`the relay is running`)
	s.And(`two remotes are running in their own project trees`)
	s.And(`the Product Owner has "/" open`)
	s.When(`the Product Owner clicks the first row's session-open`)
	s.Then(`the page shows rail`)
	s.And(`the page shows sidebar`)
	s.And(`the page shows content-breadcrumb`)
	s.And(`the URL is that session's workspace home`)
	s.Done()
}

// E2E-211: A newly connected CLI appears on the open page, by the list reading again rather than the page reloading
func TestE2E211(t *testing.T) {
	s := scenarios.New(t, "E2E-211")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has "/" open`)
	s.When(`a second remote is running in its own project tree`)
	s.Then(`the second session has its own row`)
	s.And(`the page never navigated`)
	s.Done()
}

// E2E-212: A stopped CLI vanishes from the list live, leaving nothing behind — no marker, no chip, no offer to reconnect
func TestE2E212(t *testing.T) {
	s := scenarios.New(t, "E2E-212")
	s.Given(`the relay is running`)
	s.And(`two remotes are running in their own project trees`)
	s.And(`the Product Owner has "/" open`)
	s.When(`the second remote is stopped with "SIGSTOP"`)
	s.Then(`nothing on the page carries the stopped session's id`)
	s.And(`the first session has its own row`)
	s.And(`the page never navigated`)
	s.And(`no disconnected, unreachable or reconnect marker appeared at any point`)
	s.And(`no control was ever labelled with those words`)
	s.Done()
}

// E2E-213: With nothing connected the list says so honestly and says how to connect, and shows no list container at all
func TestE2E213(t *testing.T) {
	s := scenarios.New(t, "E2E-213")
	s.Given(`the relay is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page shows sessions-empty`)
	s.And(`sessions-empty matches (?i)no sessions connected`)
	s.And(`sessions-empty matches true-bdd remote`)
	s.And(`the page shows exactly 0 session-row`)
	s.And(`the page shows exactly 0 sessions-list`)
	s.Done()
}

// E2E-214: The empty frame keeps the design language rather than falling back to bare text
func TestE2E214(t *testing.T) {
	s := scenarios.New(t, "E2E-214")
	s.Given(`the relay is running`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page paints a top bar from the token "--gradient-spiral-soft"`)
	s.And(`the wordmark tracks the token "--text-inverse" when it is changed`)
	s.And(`sessions-empty resolves "color" from the token "--text-muted"`)
	s.Done()
}

// E2E-215: Sessions are listed oldest first and stay in that order across live refreshes
func TestE2E215(t *testing.T) {
	s := scenarios.New(t, "E2E-215")
	s.Given(`the relay is running`)
	s.And(`two remotes are running in their own project trees`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the rows read oldest first by connect time`)
	s.And(`the rows still read oldest first after a live refresh`)
	s.And(`the rows still read oldest first after a second live refresh`)
	s.Done()
}

// E2E-216: The empty state waits for an answer, so a list still loading never flashes that nothing is connected
func TestE2E216(t *testing.T) {
	s := scenarios.New(t, "E2E-216")
	s.Given(`the relay is running`)
	s.And(`the sessions read is held open`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page issued a sessions read`)
	s.And(`the page shows exactly 0 sessions-empty`)
	s.And(`releasing the read with no sessions shows sessions-empty`)
	s.Done()
}

// E2E-217: The list calls itself unavailable only after failures have persisted, and returns on its own when they stop
func TestE2E217(t *testing.T) {
	s := scenarios.New(t, "E2E-217")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has "/" open`)
	s.When(`the sessions read begins failing`)
	s.Then(`the page shows exactly 0 sessions-unavailable for the first 22 seconds`)
	s.And(`the page shows sessions-unavailable within 50 seconds`)
	s.And(`sessions-unavailable matches (?i)unavailable|unable to load`)
	s.And(`the page shows exactly 0 session-row`)
	s.And(`letting the read succeed again brings the row back and clears the notice`)
	s.Done()
}

// E2E-218: A read that hangs is a failure too, so the list is not held silent forever by a request that never answers
func TestE2E218(t *testing.T) {
	s := scenarios.New(t, "E2E-218")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the Product Owner has "/" open`)
	s.When(`the sessions read begins hanging`)
	s.Then(`the page shows sessions-unavailable within 80 seconds`)
	s.And(`the page shows exactly 0 session-row`)
	s.And(`letting the read succeed again brings the row back and clears the notice`)
	s.Done()
}

// E2E-219: An answer that cannot be understood is a failure, never the honest empty state, because nothing-is-connected is a claim and not a fallback
func TestE2E219(t *testing.T) {
	s := scenarios.New(t, "E2E-219")
	s.Given(`the relay is running`)
	s.And(`the sessions read answers 200 with a body that is not a session list`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page shows exactly 0 sessions-empty for 8 seconds`)
	s.And(`a genuine empty answer then shows sessions-empty`)
	s.Done()
}

// E2E-220: The sessions home wears its own frame — a gradient bar, the wordmark and tagline, one heading, rows with their anatomy
func TestE2E220(t *testing.T) {
	s := scenarios.New(t, "E2E-220")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page paints a top bar from the token "--gradient-spiral-soft"`)
	s.And(`the wordmark tracks the token "--text-inverse" when it is changed`)
	s.And(`the page holds a visible tagline matching (?i)spec-anchored cli`)
	s.And(`the page shows exactly 1 heading of level 1`)
	s.And(`the page's heading has text "Sessions"`)
	s.And(`the page shows session-row > session-folder`)
	s.And(`the page shows session-row > session-meta`)
	s.And(`the page shows session-row > session-version`)
	s.Done()
}

// E2E-221: None of the workspace shell leaks onto the sessions home, and the retired test-connection control stays retired
func TestE2E221(t *testing.T) {
	s := scenarios.New(t, "E2E-221")
	s.Given(`the relay is running`)
	s.And(`a remote is running`)
	s.And(`the viewport is 1440x900`)
	s.When(`the Product Owner opens "/"`)
	s.Then(`the page shows exactly 0 rail`)
	s.And(`the page shows exactly 0 sidebar`)
	s.And(`the page shows exactly 0 app-shell`)
	s.And(`the page shows exactly 0 workspace-main`)
	s.And(`the page offers no test-connection control, by testid or by name`)
	s.Done()
}
