package lint

import (
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"
)

// The budget. Prose is argument and argument compresses; a block scheme —
// pseudocode, a table, a diagram — is already the compressed form, and
// squeezing it turns it back into the paragraphs this gate exists to remove.
const (
	maxProse = 3
	maxBlock = 15
)

// Indentation is the test because Go already encodes it: in a gofmt'd doc
// comment an indented line is a preformatted block, so gofmt maintains the
// distinction for free.
const (
	blockIndentTab   = "\t"
	blockIndentSpace = "    "
)

// generatedScanLines is how far down the `// Code generated` banner can sit.
const generatedScanLines = 5

var (
	commentRE   = regexp.MustCompile(`^[[:space:]]*(//|#)`)
	generatedRE = regexp.MustCompile(`(?m)^// Code generated`)
)

// A finding is one comment run over one of the two budgets.
type finding struct {
	file string
	line int
	text string
}

func (f finding) String() string {
	return fmt.Sprintf("%s:%d: %s", f.file, f.line, f.text)
}

// Comments reports every comment run over budget in the named files, or in
// every .go/.sh/.yaml/.yml file the repository tracks when none are named.
func Comments(out io.Writer, files []string) error {
	goPaths, hashPaths := commentPathspecs(files)

	var found []finding

	for _, group := range []struct {
		specs []string
		isGo  bool
	}{{goPaths, true}, {hashPaths, false}} {
		if len(group.specs) == 0 {
			continue
		}

		scanned, err := scanTracked(group.specs, group.isGo)
		if err != nil {
			return err
		}

		found = append(found, scanned...)
	}

	return reportComments(out, found)
}

// commentPathspecs splits the named files by comment marker; no name means
// the whole repository, which is what the commit gate passes.
func commentPathspecs(files []string) ([]string, []string) {
	if len(files) == 0 {
		return []string{"*.go"}, []string{"*.sh", "*.yaml", "*.yml"}
	}

	var goPaths, hashPaths []string

	for _, file := range files {
		switch {
		case strings.HasSuffix(file, ".go"):
			goPaths = append(goPaths, file)
		case strings.HasSuffix(file, ".sh"),
			strings.HasSuffix(file, ".yaml"),
			strings.HasSuffix(file, ".yml"):
			hashPaths = append(hashPaths, file)
		}
	}

	return goPaths, hashPaths
}

// scanTracked walks the files matching these pathspecs, skipping the trees
// this gate does not own and the files it did not write.
func scanTracked(specs []string, isGo bool) ([]finding, error) {
	paths, err := trackedFiles(specs...)
	if err != nil {
		return nil, err
	}

	var found []finding

	for _, path := range paths {
		if excludedTree(path) {
			continue
		}

		src, err := os.ReadFile(path)
		if err != nil {
			continue
		}

		// Generated by `true-bdd build tests --fix` and never hand-edited.
		if generatedRE.Match(head(src, generatedScanLines)) {
			continue
		}

		found = append(found, scanComments(path, string(src), isGo)...)
	}

	return found, nil
}

// scanComments is the whole gate: runs of comment lines, each classified and
// counted, flushed at the first line that is not one.
func scanComments(path, src string, isGo bool) []finding {
	scan := &commentScan{path: path, isGo: isGo, atTop: true}

	for index, line := range splitLines(src) {
		// A shebang is not a comment run, and does not end the header either.
		if index == 0 && strings.HasPrefix(line, "#!") {
			continue
		}

		if marker := commentRE.FindString(line); marker != "" {
			scan.open(index + 1)
			scan.count(line[len(marker):])

			continue
		}

		scan.flush(line)

		if strings.TrimSpace(line) != "" {
			scan.atTop = false
		}
	}

	scan.flush("")

	return scan.found
}

// commentScan is one file's walk: the run being counted, and whether it began
// before any content line.
type commentScan struct {
	path     string
	isGo     bool
	atTop    bool
	runAtTop bool
	start    int
	prose    int
	block    int
	found    []finding
}

func (s *commentScan) open(line int) {
	if s.prose+s.block == 0 {
		s.start, s.runAtTop = line, s.atTop
	}
}

func (s *commentScan) count(body string) {
	if strings.HasPrefix(body, blockIndentTab) || strings.HasPrefix(body, blockIndentSpace) {
		s.block++

		return
	}

	s.prose++
}

// flush judges the finished run against the budgets. next is the line that
// ended it, because in Go that is what identifies a package doc comment.
func (s *commentScan) flush(next string) {
	if s.prose+s.block == 0 {
		return
	}

	// The file's own manual is a different genre from annotation, and both
	// `go doc` and a script's header are where this repo already keeps one.
	exempt := s.runAtTop
	if s.isGo {
		exempt = strings.HasPrefix(next, "package ")
	}

	if !exempt && s.prose > maxProse {
		s.found = append(s.found, finding{s.path, s.start,
			fmt.Sprintf("%d lines of prose (max %d)", s.prose, maxProse)})
	}

	// The block cap binds even on an exempt header: past 15 lines it is a
	// program with worse syntax, and belongs in a README.
	if s.block > maxBlock {
		s.found = append(s.found, finding{s.path, s.start,
			fmt.Sprintf("%d-line block scheme (max %d)", s.block, maxBlock)})
	}

	s.prose, s.block = 0, 0
}

func reportComments(out io.Writer, found []finding) error {
	if len(found) == 0 {
		_, _ = fmt.Fprintf(out, "lint-comments: OK (all comments within %d prose / %d block lines)\n",
			maxProse, maxBlock)

		return nil
	}

	for _, item := range found {
		_, _ = fmt.Fprintf(out, "    %s\n", item)
	}

	_, _ = fmt.Fprintf(out, `
lint-comments: %d comment(s) over budget (%d prose, %d block).
Cut argument, keep the fact. A fact worth its line names where it was
learned (PR #, comment id) and sits at the line it guards, once — the
narrative goes to docs/for_further/.
`, len(found), maxProse, maxBlock)

	return ErrFailed
}
